name: masterg
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  accordion: ^2.5.1
  bloc: ^7.2.1
  cached_network_image: ^3.2.1
  calendar_strip: ^1.0.6
  camera: ^0.9.7+1
  camerawesome: ^0.3.0+1
  change_app_package_name: ^1.1.0
  charts_flutter: ^0.12.0
  comment_box: ^0.0.17
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  double_back_to_close: ^2.0.0
  entry: ^0.0.6
  equatable: ^2.0.3
  expandable: ^5.0.1
  ffmpeg_kit_flutter: 4.5.1-LTS
  file_picker: ^4.5.1
  flick_video_player: ^0.4.0-dev.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_cached_pdfview: ^0.4.1
  flutter_countdown_timer: ^4.1.0
  flutter_downloader: ^1.8.1
  flutter_html: ^3.0.0-alpha.3
  flutter_inappwebview: ^5.4.3+7
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^9.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.0.1
  flutter_pdfview: ^1.2.2
  flutter_svg: ^1.0.0
  focused_menu: ^1.0.5
  font_awesome_flutter: ^10.1.0
  grouped_list: ^5.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  injector: ^2.0.0
  intl: ^0.17.0
  keyboard_actions: ^4.0.0
  open_file: ^3.2.1
  overlay_support: ^2.0.0
  package_info_plus: ^1.4.2
  path: any
  percent_indicator: ^4.2.2
  permission_handler: ^9.2.0
  photo_view: ^0.14.0
  pin_code_text_field: ^1.8.0
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  rename_app: ^1.0.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  stop_watch_timer: ^1.4.0
  syncfusion_flutter_gauges: ^20.1.57
  syncfusion_flutter_sliders: ^20.1.57
  url_launcher: ^6.1.2
  video_player: ^2.4.2
  video_thumbnail: ^0.5.0
  video_trimmer: ^1.1.3
  visibility_detector: ^0.3.3
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.0

dependency_overrides: null

dev_dependencies:
  dart_code_metrics: ^4.16.0
  # change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/policy.html
    - assets/terms.html

  fonts:
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans_SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: OpenSans_Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: DMSans_Bold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
    - family: DMSans_Regular
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
