const EN_TEXT = {
  "benefits": "Benefits",
  "alert": "Alert",
  "coin_history_title": "Coin History",
  "login": "Login",
  "logout": "Logout",
  "edit_portfolio": "Edit Portfolio",
  "resumelearning": "Resume Learnings",
  "no": "No",
  "yes": "yes",
  "profile_title": "Profile",
  "myassignments": "My Assignments",
  "myassessments": "Daily Quiz",
  "cancel": "Cancel",
  "take_a_picture": "Take a picture",
  "pick_from_gallery": "Pick from gallery",
  "term_and_condition": "Terms & Condition",
  "recent_activity": "Recent Activities",
  "ok": "Ok",
  "attachFile": "Attach file",
  "loading": "Loading...",
  "enter_login_text":
      "Enter your mobile number, we will send you OTP to verify later",
  "request_otp": "Request OTP",
  "create_an_account": "Create an Account",
  "verification_title": "Enter OTP that sent to",
  "submit": "Submit",
  "resend": "Re-send",
  "code_in": "OTP in",
  "engangement": "Engangement",
  "dealer": "Dealer",
  "select_section": "Select The Section",
  "announcements": "Announcements",
  "learnNewEveryday": "Learn New Everyday",
  "topPicksCourses": "Top Picks For you",
  "recommendedCourses": "Courses Recommended for you",
  "otherLearnerCourses": "Learn what other MasterG's are learning",
  "shortCourses": "Popular Short Courses",
  "highlyRatedCourses": "Highly Rated Courses",
  "myclasses": "My Classes",
  "byInstructorName": "by Instructor Name",
  "mostViewedCourses": "Most Viewed Courses",
  "training": "My Courses",
  "mandatory_courses": "Mandatory Courses",
  "library": "Library",
  "analytics": "Analytics",
  "my_certificates": "My Certificates",
  "asking_rate_calculator": "Asking Rate Calculator",
  "create_a_session": "Create A Session",
  "scheduled_sessions": "My Classes",
  "feedback": "Feedback",
  "survey": "Survey",
  "language": "Language",
  "account_settings": "My Space Settings",
  "FAQs": "FAQs",
  "contact_us": "Contact Us",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "terms_and_conditions": "Terms and Conditions",
  "privacy_policy": "Privacy Policy",
  "view_all": "View all",
  "start_survey": "Start Survey",
  "announcement_filters": "Announcement Filters",
  "write_feedback": "Write A Feedback",
  "write_an_idea": "Write an Idea",
  "library_filters": "Library Filters",
  "rewards": "Rewards",
  "games": "Games",
  "partner_benefits": "Partner Benefits",
  "storyboard": "Storyboard",
  "your_points": "Your Points",
  "likes": "Likes",
  "share": "Share",
  "win_upto": "Win upto",
  "points": "Points",
  "search_game": "Search Game",
  "your_best_score": "Your Best Score",
  "play_now": "Play Now",
  "how_to_play": "How To Play",
  "your_score": "Your Score",
  "game_over": "Game Over",
  "play_again": "Play Again",
  "view_coin_history": "View Coin History",
  "reward_catalogue": "Reward Catalogue",
  "claimed_reward": "Claimed Reward",
  "coins": "Coins",
  "reedem": "Reedem",
  "notifications": "Notifications",
  "profile": "My Space",
  "address": "Address",
  "social_media": "Social Media",
  "add_family_member": "Add Family Member",
  "business_details": "Business Details",
  "business_address": "Business Address",
  "landmark": "Landmark",
  "post_office": "Post Office",
  "city": "City",
  "state": "State",
  "save_changes": "Save Changes",
  "whatsapp": "Whatsapp",
  "facebook_id": "Facebook ID",
  "twitter_handle": "Twitter handle",
  "gst_number": "GST number",
  "pan_number": "PAN number",
  "save": "Save",
  "bonding": "Bonding",
  "connection": "Connection",
  "recoginsion": "Recoginsion",
  "definition": "Definition",
  "eligibility_membership": "Eligibility and Membership",
  "benfits_text": "Benfits, Priviledges and Rewards",
  "General": "General",
  "the_points": "How can I redeem the points",
  "change_language": "How to change language",
  "membership_benefits": "What is Membership benefits",
  "change_my_number": "How can I change my number",
  "previous": "Previous",
  "next": "Next",
  "app_language": "App Language",
  "content_language": "Content Language",
  "choose_app_language": "Choose your App Language",
  "choose_content_language": "Choose Content Language",
  "added_family_members": "Added Family Members",
  "relation_with_family": "Relation with Family",
  "first_name": "First Name",
  "last_name": "Last Name",
  "date_of_birth": "Date of Birth",
  "mobile_number": "Mobile Number",
  "occupation": "Occupation",
  "email_address": "Email Address",
  "email_address_error": "Email address is invalid",
  "title": "Title",
  "topic": "Topic",
  "description": "Description",
  "select_app_language": "Select App Language",
  "language_option": "You can change it later from the Language\noption",
  "select_content_language": "Select Content Language",
  "update_version_title": "Update available",
  "update_version_text1":
      "A new version is available. Would you like to update the app?",
  "update_version_text2": "A new version is available. Please update the app.",
  "forgot_pass": "Forgot password",
  "photo_alert": "Set a photo",
  "take_a_video": "Take a Video",
  "pick_a_video": "Pick a Video",
  "pick_a_file": "Pick a File",
  "verification": "Verification",
  "family_member": "Family Member",
  "edit": "Edit",
  "delete": "Delete",
  "you_can_change_langauge": "You can change it later from the Language option",
  "insta": "Instagram Handle",
  "submitted": "Submitted",
  "choose_language": "Choose Language",
  "update_profile": "Update My Space",
  "gender": "Gender",
  "male": "Male",
  "female": "Female",
  "faqTitle1": "I am not able to access chapters/ module.",
  "faqTitle2": "I am not able to access Live class.",
  "faqTitle3":
      "Can I change the language of the content in between after logging in the app ?",
  "faqTitle4":
      "Once I choose any language, do I need to choose it every time I open the app ?",
  "faqTitle5":
      "What will happen to the trainings which are already completed in previous app ? ",
  "faqTitle6": "Can we download the content from the app?",
  "faqTitle7":
      "In asking rate calculator, some users have weekly off on Mondays/Tuesday etc. How do we track that?",
  "faq2": "A. Live class in a training -\nIf you want to see all the live classes in specific training, Follow the link from TRAINING, just click on the live class tab and you can join the available live classes.\n\n"
      "B. Live class in a module -\nIf you want to see the live classes specific to the MODULE, just click on the training and you will come across list of all MODULES. Navigate through the module and you will see the list of all trainings. You can then join the available live class.\n\n"
      "C. Live class in Announcement -\nIf you want to see the live classes specific to the Highlights, just click on the Highlights. Navigate through the listed activities. You can then join the available live classes.\n\n"
      "D. Not able to view Live session –\nIn case you are not able to view the live session, check the block in top right browser window. Click on the block and check allow. ",
  "faq1":
      "Follow the link from TRAINING, you will find the list of all trainings. Just click on the specific training and you can navigate through all MODULES.",
  "faq3":
      "Yes, Go to the language option in the menu and there you can choose the language both for App as well as content.",
  "faq4":
      "No, only once the user will have to choose the language. It will remain saved in the app. But the user can choose to change the language.",
  "faq5":
      "It will remain completed in the reports but to show it on the app, it might take some time as it has to be done from the backend.",
  "faq6": "No, the download option is not available in the app.",
  "faq7":
      "As a common standard we have considered weekly off on Sunday and keeping 6 days a week for the man-days calculation. Also mentioned is the approx. man-days available.",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "Idea Factory",
  "Create_Live_Class": "Create Live Class",
  "Schedule_Now": "Schedule Now",
  "Create_a_Session": "Create a Session",
  "Select_Title": "Select Title",
  "Select_Date": "Select Date",
  "Invite_learners": "Invite learners",
  "Members_added": "Members added",
  "Publish_Now": "Publish Now",
  "Save_as_draft": "Save as draft",
  "Schedules_Sessions": "Schedules Sessions",
  "Upcoming_Sessions": "Upcoming Classes",
  "Draft": "Draft",
  "What_to_expect": "What to expect",
  "Start_date": "Start date",
  "End_date": "End date",
  "Modules_included": "Modules included",
  "List_of_modules": "List of modules",
  "Content": "Content",
  "Scorm": "Scorm",
  "Live_sessions": "Live sessions",
  "Videos": "Videos",
  "Notes": "Notes",
  "Assignment": "Assignment",
  "Assessment": "Assessment",
  "Define_your_self": "Define your self-goals and boost your improvement",
  "Certification": "Certification",
  "My_Analytics": "My Analytics",
  "Team_Analytics": "Team Analytics",
  "KPI_Analytics": "KPI Analytics",
  "Course_level_Analysis": "Course level Analysis",
  "Module_level_Analysis": "Module level Analysis",
  "Leaderboard": "Leaderboard",
  "Switch_to_modules": "Switch to modules",
  "Switch_to_leaderboard": "Switch to leaderboard",
  "Completed": "Completed",
  "Score": "Score",
  "Course_name": "Course name",
  "KPIs_assigned": "KPIs assigned",
  "Monthly_performance": "Monthly performance",
  "My_certificates": "My certificates",
  "Your_medals": "Your medals",
  "Certificates": "Certificates",
  "Set_your_goals":
      "Set your goals in the calculator below & track the rate required to finish the goal",
  "Select_your_goal": "Select your goal",
  "Calculate_now": "Calculate now",
  "Billed_outlets": "Billed outlets",
  "Targeted_outlets": "Targeted outlets",
  "Target": "Target",
  "Currently_achieved": "Currently achieved",
  "Total_MSS_Points": "Total MSS Points",
  "Calculated_asking_rate": "Calculated asking rate",
  "Manage_your_everyday": "Manage your everyday to achieve bigger results",
  "For_next": "For next",
  "Days": "Days",
  "Details": "Details",
  'time': "Time",
  'duration': "Duration",
  'verify_your_mobile': 'Verify your mobile',
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/Create account to continue',
  'phone_number': 'Phone number',
  'your_mobile_number': 'Your mobile number',
  'continue': 'Continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and Conditions & Privacy Policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  'assessments': 'My Assessments',
  'assignments': 'My Assignments',
  'create_post': 'Create Post',
  'ghome': 'GHome',
  'gschool': 'GSchool',
  'greels': 'GReels',
  'gcarvaan': 'GCaravan',
  'create_reels': 'Create Reels',
  'like': 'Like',
  'comment': 'Comment',
  'email': 'Email',
  'phone': 'Phone',
  'reels': 'Reels',
  'views': 'View',
  'write_your_post': 'Write your post',
  'add_more': 'Add more',
  'tell_us_about_yourself': "Tell us about yourself",
  'category_not_found': "Category Not Found!",
  'there_are_no_recent_activity': 'There are no recent activities!!',
  'apni_padhai_jaari_rakein': 'Resume Learning',
  'my_courses': 'My Courses',
  'my_quiz': 'My Quiz',
  'completed': 'Completed'
};

const TA_TEXT = {
  'recommendedCourses': 'பரிந்துரைக்கப்பட்ட படிப்புகள்',
  'learnNewEveryday': 'தினமும் புதிதாக கற்றுக் கொள்ளுங்கள்',
  'otherLearnerCourses':
      'மற்ற MasterGகள் என்ன கற்றுக்கொள்கிறார்கள் என்பதை அறிக',
  'verify_your_mobile': 'உங்கள் மொபைலைச் சரிபார்க்கவும்',
  "alert": "எச்சரிக்கை",
  "login": "உள்நுழை",
  "logout": "வெளியேறு",
  "edit_portfolio": "Edit Portfolio",
  "no": "இல்லை",
  "yes": "ஆம்",
  "profile_title": "சுயவிவரம்",
  "cancel": "ரத்துசெய்",
  "take_a_picture": "படம் எடு",
  "pick_from_gallery": "கேலரியில் இருந்து எடுக்கவும்",
  "ok": "சரி",
  "loading": "லோடிங்…",
  "submit": "சமர்ப்பிக்கவும்",
  "announcements": "அறிவிப்புகள்",
  "training": "பயிற்சிகள்",
  "mandatory_courses": "கட்டாய படிப்புகள்",
  "library": "லைப்ரரி",
  "analytics": "பகுப்பாய்வு",
  "my_certificates": "எனது சான்றிதழ்கள்",
  "asking_rate_calculator": "ரேட் கால்குலேட்டரைக் கேட்க",
  "create_a_session": "செஷனை உருவாக்கு",
  "scheduled_sessions": "ஷெட்யூல்ட் செஷன்ஸ்",
  "feedback": "பின்னூட்டம்",
  "survey": "சர்வே",
  "attachFile": "Attach file",
  "language": "மொழி",
  "account_settings": "அக்கவுண்ட் செட்டிங்ஸ்",
  "FAQs": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
  "contact_us": "தொடர்பு கொள்ள",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "அனைத்தையும் காட்டு",
  "start_survey": "சர்வேவை தொடங்கு",
  "announcement_filters": "அறிவிப்பு ஃபில்டெர்ஸ்",
  "write_feedback": "தங்கள் கருத்தை எழுதவும்",
  "write_an_idea": "ஒரு யோசனை எழுத",
  "library_filters": "லைப்ரரி ஃபில்டெர்ஸ்",
  "notifications": "அறிவிப்புகள்",
  "profile": "சுயவிவரம்",
  "address": "முகவரி",
  "landmark": "லேண்ட்மார்க்",
  "post_office": "தபால் அலுவலகம்",
  "city": "நகரம்",
  "state": "மாநிலம்",
  "save_changes": "திருத்தங்களை சேமி",
  "save": "சேமி",
  "app_language": "பயன்பாட்டு மொழி",
  "content_language": "உள்ளடக்க மொழி",
  "choose_app_language": "பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்",
  "choose_content_language": "உள்ளடக்க மொழியைத் தேர்ந்தெடுக",
  "first_name": "பெயரின் முற்பகுதி",
  "last_name": "பெயரின் பிற்பகுதி",
  "date_of_birth": "பிறந்த தேதி",
  "mobile_number": "கைபேசி எண்",
  "email_address": "மின்னஞ்சல் முகவரி",
  "email_address_error": "Email address is invalid",
  "title": "டைட்டில்",
  "topic": "தலைப்பு",
  "description": "விளக்கம்",
  "select_app_language": "பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்",
  "language_option":
      "நீங்கள் அதை பின்னர் லேங்குவேஜ் ஆப்ஷனில் இருந்து மாற்றலாம்",
  "select_content_language": "உள்ளடக்க மொழியைத் தேர்ந்தெடுக",
  "update_version_title": "அப்டெட் கிடைக்கிறது",
  "update_version_text1":
      "புதிய அப்டெட் கிடைக்கிறது. ஆப்பை அப்டெட் செய்ய விரும்புகிறீர்களா?",
  "update_version_text2": "புதிய அப்டெட் கிடைக்கிறது. ஆப்பை அப்டெட் செய்யவும்",
  "forgot_pass": "பாஸ்வேர்டை மறந்துவிட்டீர்களா",
  "photo_alert": "புகைப்படத்தை வைக்க",
  "take_a_video": "வீடியோவை எடுக்க",
  "pick_a_video": "வீடியோவைத் தேர்ந்தெடு",
  "pick_a_file": "ஒரு பைல்-ஐ தேர்ந்தெடு",
  "verification": "சரிபார்ப்பு",
  "you_can_change_langauge":
      "நீங்கள் இதை லேங்க்வேஜ் ஆப்ஷனில் பின்னர் மாற்றலாம்",
  "submitted": "சமர்ப்பிக்கப்பட்டது",
  "choose_language": "மொழியைத் தேர்வுசெய்க",
  "update_profile": "புதுப்பிப்பு",
  "gender": "பாலினம்",
  "male": "ஆண்",
  "female": "பெண்",
  "faqTitle1": "என்னால் அத்தியாயங்கள் / மாட்யூல்களை அணுக முடியவில்லை.",
  "faqTitle2": "லைவ்  கிளாஸை என்னால் அணுக முடியவில்லை எனில்.",
  "faqTitle3":
      "ஆப்பின் உள்நுழைந்த பிறகு இடையில் உள்ளடக்கத்தின் மொழியை மாற்ற முடியுமா?",
  "faqTitle4":
      "நான் எந்த மொழியையும் தேர்வு செய்தால், ஒவ்வொரு முறையும் ஆப்பை திறக்கும் போது அதைத் தேர்வு செய்ய வேண்டுமா?",
  "faqTitle5":
      "முந்தைய ஆப்பில் ஏற்கனவே முடிக்கப்பட்ட ட்ரெயினிங்களுக்கு என்ன ஆகும்? ",
  "faqTitle6": "ஆப்பில்லிருந்து கண்டெண்ட்டை டவுன்லோட் செய்ய முடியுமா?",
  "faqTitle7":
      "விகித கால்குலேட்டரைக் கேட்கும் போது, ​​சில பயனர்கள் திங்கள் / செவ்வாய்க் கிழமைகளில் வாராந்திர விடுமுறை எடுக்கிறார்கள். அதை எவ்வாறு கண்காணிப்பது?",
  "faq2": "A. ட்ரெயினிங்கில் லைவ் கிளாஸ் -\nகுறிப்பிட்ட ட்ரெயினிங்கில் அனைத்து லைவ் கிளாஸ்களையும் நீங்கள் காண விரும்பினால், ட்ரெயினிங்கிலிருந்து லிங்க்கை பின்தொடர்ந்து, லைவ் கிளாஸ் டேப்-ஐ கிளிக் செய்து, கிடைக்கக்கூடிய  லைவ் கிளாஸ்களில் சேரலாம்.\n\n"
      "B. மாட்யூலில் லைவ் கிளாஸ் -\nநீங்கள் மாட்யூலில் குறிப்பிட்ட லைவ் கிளாஸ்களைப் பார்க்க விரும்பினால், ட்ரெயினிங்கை கிளிக் செய்தால், எல்லா மாட்யூல்களின் பட்டியலையும் நீங்கள் காண்பீர்கள். மாட்யூல் வழியாக சென்று, நீங்கள் அனைத்து ட்ரெயினிங்களின் பட்டியலையும் காண்பீர்கள். பின் நீங்கள் கிடைக்கக்கூடிய லைவ் கிளாஸ்களில் சேரலாம்.\n\n"
      "C. லைவ் கிளாஸ்களை பற்றிய அறிவுப்பு -\nஹைலைட்ஸ்களில் ஒரு குறிப்பிட்ட லைவ் கிளாஸ்களை நீங்கள் காண விரும்பினால், ஹைலைட்ஸ்களைக் கிளிக் செய்து லிஸ்டெட் ஆக்டிவிட்டிஸ்களுக்கு செல்லவும். பின் நீங்கள்  கிடைக்கக்கூடிய  லைவ் கிளாஸ்களில் சேரலாம்.\n\n"
      "D. லைவ் செஷனைக் காண முடியவில்லை –\nநீங்கள் லைவ் செஷனைக் காண முடியாவிட்டால், மேல் வலது  புற விண்டோவில் அமைந்த  உள்ள பிளாக்கை சரிபார்க்கவும். பிளாக்கை கிளிக் செய்த பின் அனுமதி அளிக்கவும்.  படம்: https://swayam.pvmi.in/img/step.jpg",
  "faq1":
      "ட்ரெயினிங்கில் இருந்து லிங்க்கை பின்தொடரவும், எல்லா ட்ரெயினிங் பட்டியலையும் நீங்கள் காண்பீர்கள். குறிப்பிட்ட ட்ரெயினிங்கை கிளிக் செய்தால், நீங்கள் அனைத்து மாட்யூல்களுக்கும் செல்லலாம்.",
  "faq3":
      "ஆம், மெனுவில் உள்ள மொழி விருப்பத்திற்குச் சென்று, அங்கு நீங்கள் ஆப் மற்றும் கண்டெண்ட் ஆகிய இரண்டையும் தேர்வு செய்யலாம்.",
  "faq4":
      "இல்லை, ஒரு முறை மட்டுமே பயனர் மொழியைத் தேர்வு செய்ய வேண்டும். இது ஆப்பில் சேமிக்கப்படும். ஆனால் பயனர் மொழியை மாற்ற தேர்வு செய்யலாம்.",
  "faq5":
      "இது  ரிப்போர்ட்ஸில்  நிறைவடையும், ஆனால் அதை ஆப்பில் காண்பிக்க, பின்தளத்தில் இருந்து செய்ய வேண்டியிருப்பதால் சிறிது நேரம் ஆகலாம்.",
  "faq6": "இல்லை, டவுன்லோட் ஆப்ஷன் ஆப்பில் இல்லை.",
  "faq7":
      "ஒரு பொதுவான தரமாக, ஞாயிற்றுக்கிழமை வாராந்திர விடுமுறை மற்றும் மனித நாட்களின் (man-days) கணக்கீட்டிற்கு வாரத்தில் 6 நாட்கள் வைத்திருக்கிறோம். ஒரு தோராயமான குறிப்பிடப்பட்டுள்ள  மனித நாட்கள் கிடைக்கும்.",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "ஐடியா ஃபேக்டரி",
  "Create_Live_Class": "நேரடி வகுப்பை உருவாக்கு",
  "Schedule_Now": "இப்போது ஷெட்யூல் செய்",
  "Create_a_Session": "செஷனை உருவாக்கு",
  "Select_Title": "தலைப்பைத் தேர்ந்தெடுக்கவும்",
  "Select_Date": "தேதியை தேர்ந்தெடுக்கவும்",
  "Invite_learners": "கற்பவர்களை அழைக்கவும்",
  "Members_added": "சேர்க்கப்பட்ட உறுப்பினர்கள்",
  "Publish_Now": "இப்போது வெளியிடுக",
  "Save_as_draft": "டிராப்ட்டாக சேமி",
  "Schedules_Sessions": "ஷெட்யூல்ட் செஷன்ஸ்",
  "Upcoming_Sessions": "வரவிருக்கும் செஷன்ஸ்",
  "Draft": "டிராப்ட்",
  "What_to_expect": "என்ன எதிர்பார்க்கலாம்",
  "Start_date": "தொடக்க தேதி",
  "End_date": "கடைசி தேதி",
  "Modules_included": "சேர்க்கப்பட்டுள்ள மாட்யூல்ஸ்",
  "List_of_modules": "தொகுதிகளின் பட்டியல்",
  "Content": "உள்ளடக்கம்",
  "Scorm": "ஸ்கார்ம்",
  "Live_sessions": "லைவ் செஷன்ஸ்",
  "Videos": "வீடியோக்கள்",
  "Notes": "குறிப்புகள்",
  "Assignment": "பணி",
  "Assessment": "மதிப்பீடு",
  "Define_your_self":
      "உங்கள் சுய இலக்குகளை வரையறுத்து உங்கள் முன்னேற்றத்தை அதிகரிக்கவும்",
  "Certification": "சான்றிதழ்",
  "My_Analytics": "எனது அனலிட்டிக்ஸ்",
  "Team_Analytics": "டீம் அனலிட்டிக்ஸ்",
  "KPI_Analytics": "கேபிஐ அனலிட்டிக்ஸ்",
  "Course_level_Analysis": "கோர்ஸ் லெவல் அனலிசிஸ்",
  "Module_level_Analysis": "மாட்யூல் லெவல் அனலிசிஸ்",
  "Leaderboard": "லீடர்போர்டு",
  "Switch_to_modules": "மாட்யூல்களுக்கு மாறவும்",
  "Switch_to_leaderboard": "லீடர்போர்டுக்கு மாறவும்",
  "Completed": "நிறைவு",
  "Score": "ஸ்கோர்",
  "Course_name": "படிப்பின் பெயர்",
  "KPIs_assigned": "ஒதுக்கப்பட்டுள்ள கேபிஐக்கள்",
  "Monthly_performance": "மாத செயல்திறன்",
  "My_certificates": "எனது சான்றிதழ்கள்",
  "Your_medals": "உங்கள் பதக்கங்கள்",
  "Certificates": "சான்றிதழ்கள்",
  "Set_your_goals":
      "கீழே உள்ள கால்குலேட்டரில் உங்கள் இலக்குகளை அமைத்து, இலக்கை முடிக்க தேவையான விகிதத்தைக் கண்காணிக்கவும்",
  "Select_your_goal": "உங்கள் இலக்கைத் தேர்ந்தெடுக்கவும்",
  "Calculate_now": "இப்போது கணக்கிடுங்கள்",
  "Billed_outlets": "பில்ட் அவுட்லேட்ஸ்",
  "Targeted_outlets": "டார்கேட்டெட் அவுட்லேட்ஸ்",
  "Target": "டார்கேட்",
  "Currently_achieved": "தற்போது அடையப்பட்டுள்ளவைகள்",
  "Total_MSS_Points": "மொத்த எம்எஸ்எஸ் பாயிண்ட்ஸ்",
  "Calculated_asking_rate": "கணக்கிடப்பட்ட கேட்கும் வீதம்",
  "Manage_your_everyday":
      "பெரிய முன்னேற்றத்தை அடைய உங்கள் அன்றாடத்தை நிர்வகிக்கவும்",
  "For_next": "அடுத்தது",
  "Days": "நாட்கள்",
  "Details": "விவரங்கள்",
  'time': "நேரம்",
  'duration': "காலம்",
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/ create account to continue',
  'phone_number': 'Phone number',
  'continue': 'continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and Conditions & Privacy Policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'verification_title': "Enter OTP that sent to",
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  "resend": "Re-send",
  "code_in": "OTP in",
  'tell_us_about_yourself': "Tell us about yourself",
};

const TE_TEXT = {
  "recommendedCourses": "సిఫార్సు చేసిన కోర్సులు",
  "learnNewEveryday": "ప్రతిరోజూ నేర్చుకోండి",
  'otherLearnerCourses': 'ఇతర MasterGలు ఏమి నేర్చుకుంటున్నారో తెలుసుకోండి',
  'verify_your_mobile': 'మీ మొబైల్‌ని ధృవీకరించండి',
  "alert": "హెచ్చరిక",
  "login": "లాగిన్",
  "logout": "లాగ్ ఔట్",
  "edit_portfolio": "Edit Portfolio",
  "no": "లేదు",
  "yes": "అవును",
  "attachFile": "Attach file",
  "profile_title": "ప్రొఫైల్",
  "cancel": "రద్దు చేయండి",
  "take_a_picture": "ఫోటో తీయండి",
  "pick_from_gallery": "గాలరీ నుండి ఎంచుకోండి",
  "ok": "అలాగే",
  "loading": "లోడింగ్…",
  "submit": "సమర్పించు",
  "announcements": "ప్రకటనలు",
  "training": "శిక్షణలు",
  "mandatory_courses": "తప్పనిసరి కోర్సులు",
  "library": "గ్రంధాలయం",
  "analytics": "విశ్లేషణలు",
  "my_certificates": "నా ధృవపత్రాలు",
  "asking_rate_calculator": "అడిగే రేటు కాలిక్యులేటర్",
  "create_a_session": "ఒక సెషన్ ను సృష్టించండి",
  "scheduled_sessions": "షెడ్యూల్ సెషన్స్",
  "feedback": "అభిప్రాయం",
  "survey": "సర్వే",
  "language": "భాష",
  "account_settings": "ఖాతా సెట్టింగులు",
  "FAQs": "తరచుగా అడిగే ప్రశ్నలు",
  "contact_us": "మమ్మల్ని సంప్రదించండి",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "అన్నీ చూడండి",
  "start_survey": "సర్వే ప్రారంభించండి",
  "announcement_filters": "ప్రకటన ఫిల్టర్లు",
  "write_feedback": "అభిప్రాయాన్ని వ్రాయండి",
  "write_an_idea": "ఒక ఆలోచన రాయండి",
  "library_filters": "లైబ్రరీ ఫిల్టర్లు",
  "notifications": "నోటిఫికేషన్లు",
  "profile": "ప్రొఫైల్",
  "address": "చిరునామా",
  "landmark": "ల్యాండ్ మార్క్",
  "post_office": "తపాలా కార్యాలయము",
  "city": "నగరం",
  "state": "రాష్ట్రం",
  "save_changes": "మార్పులను పొందుపరుచు",
  "save": "సేవ్",
  "app_language": "యాప్ భాష",
  "content_language": "కంటెంట్ భాష",
  "choose_app_language": "అనువర్తన భాషను ఎంచుకోండి",
  "choose_content_language": "కంటెంట్ భాషను ఎంచుకోండి",
  "first_name": "మొదటి పేరు",
  "last_name": "చివరి పేరు",
  "date_of_birth": "పుట్టిన తేదీ",
  "mobile_number": "మొబైల్ నెంబర్",
  "email_address": "ఇ-మెయిల్ చిరునామా",
  "email_address_error": "Email address is invalid",
  "title": "శీర్షిక",
  "topic": "అంశం",
  "description": "వివరణ",
  "select_app_language": "యాప్ భాషను ఎంచుకోండి",
  "language_option": "మీరు దీన్ని భాషా ఎంపిక నుండి తరువాత మార్చుకోవచ్చు",
  "select_content_language": "కంటెంట్ భాషను ఎంచుకోండి",
  "update_version_title": "అప్డేట్ అందుబాటులో ఉంది",
  "update_version_text1":
      "క్రొత్త సంస్కరణ అందుబాటులో ఉంది. మీరు యాప్ ని నవీకరించాలనుకుంటున్నారా?",
  "update_version_text2":
      "క్రొత్త సంస్కరణ అందుబాటులో ఉంది. దయచేసి యాప్ ని అప్డేట్ చేయండి.",
  "forgot_pass": "పాస్ వర్డ్ మర్చిపోయా",
  "photo_alert": "ఫోటో సెట్ చేయండి",
  "take_a_video": "వీడియో తీయండి",
  "pick_a_video": "వీడియోను ఎంచుకోండి",
  "pick_a_file": "ఫైల్ ను ఎంచుకోండి",
  "verification": "ధృవీకరణ",
  "you_can_change_langauge": "మీరు దీన్ని భాషా ఎంపిక నుండి తరువాత మార్చుకోవచ్",
  "submitted": "సమర్పించబడింది",
  "choose_language": "భాషను ఎంచుకోండి",
  "update_profile": "నవీకరణ ప్రొఫైల్",
  "gender": "లింగం",
  "male": "పురుషుడు",
  "female": "స్త్రీ",
  "faqTitle1": "నేను అధ్యాయాలు / మాడ్యూల్ ను యాక్సెస్ చేయలేకపోతున్నాను.",
  "faqTitle2": "నేను లైవ్ క్లాస్ ని యాక్సెస్ చేయలేకపోతున్నాను.",
  "faqTitle3":
      "యాప్ లో లాగిన్ అయిన తర్వాత మధ్యలో కంటెంట్ యొక్క భాషను నేను మార్చవచ్చా?",
  "faqTitle4":
      "నేను ఏదైనా భాషను ఎంచుకున్న తర్వాత, నేను యాప్ ను తెరిచిన ప్రతిసారీ దాన్ని ఎంచుకోవాల్సిన అవసరం ఉందా?",
  "faqTitle5": "మునుపటి యాప్ లో ఇప్పటికే పూర్తయిన శిక్షణలకు ఏమి జరుగుతుంది? ",
  "faqTitle6": "మేము యాప్ నుండి కంటెంట్ ను డౌన్ లోడ్ చేయగలమా?",
  "faqTitle7":
      "ఆస్కింగ్ రేట్ క్యాలుకలేటర్ లో కొంతమంది వినియోగదారులకు సోమవారం/మంగళవారం వారానికి సెలవు ఉంది. మేము దానిని ఎలా ట్రాక్ చేస్తాము?",
  "faq2": "A. శిక్షణలో లైవ్ క్లాస్ -\nమీరు నిర్దిష్ట శిక్షణలో అన్ని ప్రత్యక్ష తరగతులను చూడాలనుకుంటే, 'శిక్షణ' నుండి లింక్ ను అనుసరించండి, లైవ్ క్లాస్ టాబ్ పై క్లిక్ చేయండి మరియు మీరు అందుబాటులో ఉన్న లైవ్ క్లాస్ లలో చేరవచ్చు.\n\n"
      "B. మాడ్యూల్ లో లైవ్ క్లాస్ -\nమీరు 'మాడ్యూల్'‌కు ప్రత్యేకమైన లైవ్ క్లాస్ లను చూడాలనుకుంటే, శిక్షణపై క్లిక్ చేయండి మరియు మీరు అన్ని మాడ్యూళ్ల జాబితాను చూస్తారు. మాడ్యూల్ ద్వారా నావిగేట్ చేయండి మరియు మీరు అన్ని శిక్షణల జాబితాను చూస్తారు. అప్పుడు మీరు అందుబాటులో ఉన్న లైవ్ క్లాస్ లో చేరవచ్చు.\n\n"
      "C. ప్రకటనలో లైవ్ క్లాస్ -\nమీరు ముఖ్యాంశాలకు ప్రత్యేకమైన ప్రత్యక్ష తరగతులను చూడాలనుకుంటే, ముఖ్యాంశాలపై క్లిక్ చేయండి.  జాబితా చేయబడిన కార్యకలాపాల ద్వారా నావిగేట్ చేయండి.  అప్పుడు మీరు అందుబాటులో ఉన్న ప్రత్యక్ష తరగతుల్లో చేరవచ్చు.\n\n"
      "D. ప్రత్యక్ష సెషన్ ను చాడలేకపోతున్నాను –\nఒకవేళ మీరు ప్రత్యక్ష సెషన్‌ను చూడలేకపోతే, కుడి ఎగువ బ్రౌజర్ విండోలోని బ్లాక్ ను క్లిక్ చేయండి. బ్లాక్ పై క్లిక్ చేసి అనుమతి ఇవ్వడం కోసం టిక్ చేయండి. అప్పుడు వచ్చే చిత్రం:  https://swayam.pvmi.in/img/step.jpg",
  "faq1":
      "'శిక్షణ' నుండి లింక్ ను అనుసరించండి, మీరు అన్ని శిక్షణల జాబితాను కనుగొంటారు. నిర్దిష్ట శిక్షణపై క్లిక్ చేయండి మరియు మీరు అన్ని మాడ్యూల్స్ ద్వారా నావిగేట్ చేయవచ్చు.",
  "faq3":
      "అవును, మెను లోని భాషా ఎంపికకు వెళ్లి అక్కడ మీరు యాప్ మరియు కంటెంట్ కోసం భాషను ఎంచుకోవచ్చు.",
  "faq4":
      "లేదు, వినియోగదారు ఒక్కసారి మాత్రమే భాషను ఎన్నుకోవాలి.  ఇది యాప్ లో సేవ్ చేయబడుతుంది.  కానీ వినియోగదారు భాషను మార్చడానికి వీలుంటుంది. ",
  "faq5":
      "ఇది నివేదికలలో పూర్తవుతుంది కాని దాన్ని యాప్ లో చూపించడానికి బ్యాకెండ్ నుండి పూర్తి చేయవలసి ఉన్నందున కొంత సమయం పడుతుంది.",
  "faq6": "లేదు, డౌన్ లోడ్ ఎంపిక యాప్ లో అందుబాటులో లేదు.",
  "faq7":
      "ఒక సాధారణ ప్రమాణంగా మేము ఆదివారాన్ని వారపు సెలవుగా పరిగణించాము మరియు వారంలో 6 రోజులు మనిషి-రోజుల గణన కోసం ఉంచాము. అందుబాటులో ఉన్న మనిషి-రోజులు మాత్రమే అంచనాగా ప్రస్తావించబడ్డాయి.",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "ఐడియా ఫ్యాక్టరీ",
  "Create_Live_Class": "లైవ్ క్లాస్ సృష్టించండి",
  "Schedule_Now": "ఇప్పుడు షెడ్యూల్ చేయండి",
  "Create_a_Session": "ఒక సెషన్ ను సృష్టించండి",
  "Select_Title": "శీర్షిక ఎంచుకోండి",
  "Select_Date": "తేదీని ఎంచుకోండి",
  "Invite_learners": "అభ్యాసకులను ఆహ్వానించండి",
  "Members_added": "జోడింపబడిన సభ్యులు",
  "Publish_Now": "ఇప్పుడు ప్రచురించండి",
  "Save_as_draft": "ప్రతిగా భద్రపరచుము",
  "Schedules_Sessions": "షెడ్యూల్ సెషన్స్",
  "Upcoming_Sessions": "రాబోయే సెషన్",
  "Draft": "చిత్తుప్రతి",
  "What_to_expect": "ఏమి ఆశించొచ్",
  "Start_date": "ప్రారంభపు తేది",
  "End_date": "చివరి తేది",
  "Modules_included": "చేర్చబడిన గుణకాలు",
  "List_of_modules": "గుణకాల జాబితా",
  "Content": "విషయము",
  "Scorm": "స్కార్మ్",
  "Live_sessions": "ప్రత్యక్ష సెషన్లు",
  "Videos": "వీడియోలు",
  "Notes": "గమనికలు",
  "Assignment": "అసైన్మెంట్",
  "Assessment": "",
  "Define_your_self":
      "మీ స్వీయ లక్ష్యాలను నిర్వచించండి మరియు మీ అభివృద్ధిని పెంచుకోండి",
  "Certification": "ధృవీకరణ",
  "My_Analytics": "నా విశ్లేషణలు",
  "Team_Analytics": "టీమ్ అనలిటిక్స్",
  "KPI_Analytics": "కె.పి.ఐ అనలిటిక్స్",
  "Course_level_Analysis": "కోర్సు స్థాయి విశ్లేషణ",
  "Module_level_Analysis": "మాడ్యూల్ స్థాయి విశ్లేషణ",
  "Leaderboard": "లీడర్ బోర్",
  "Switch_to_modules": "మాడ్యూళ్ళకు మారండి",
  "Switch_to_leaderboard": "లీడర్ బోర్డుకు మారండి",
  "Completed": "పూర్తయింది",
  "Score": "స్కోరు",
  "Course_name": "కోర్సు పేరు",
  "KPIs_assigned": "కేటాయించబడిన కె.పి.ఐ లు",
  "Monthly_performance": "నెలవారీ పనితీరు",
  "My_certificates": "నా ధృవపత్రాలు",
  "Your_medals": "మీ పతకాలు",
  "Certificates": "ధృవపత్రాలు",
  "Set_your_goals":
      "దిగువ ఉన్న కాలిక్యులేటర్ లో మీ లక్ష్యాలను సెట్ చేయండి మరియు లక్ష్యాన్ని పూర్తి చేయడానికి అవసరమైన రేటును ట్రాక్ చేయండి",
  "Select_your_goal": "మీ లక్ష్యాన్ని ఎంచుకోండి",
  "Calculate_now": "ఇప్పుడు లెక్కించండి",
  "Billed_outlets": "బిల్ చేయబడిన అవుట్లెట్లు",
  "Targeted_outlets": "టార్గెట్ చేయబడ్డ అవుట్లెట్లు",
  "Target": "లక్ష్యం",
  "Currently_achieved": "ప్రస్తుతం సాధించినవి",
  "Total_MSS_Points": "మొత్తం ఎమ్.ఎస్.ఎస్ పాయింట్",
  "Calculated_asking_rate": "లెక్కింపబడిన అడిగే రేటు",
  "Manage_your_everyday": "పెద్ద ఫలితాలను సాధించడానికి మీ రోజుని నిర్వహించండి",
  "For_next": "తదుపరి కోసం",
  "Days": "రోజులు",
  "Details": "వివరాలు",
  'time': "సమయం",
  'duration': "వ్యవధి",
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/ create account to continue',
  'phone_number': 'Phone number',
  'continue': 'continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and condition & privacy policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'verification_title': "Enter OTP that sent to",
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  "resend": "Re-send",
  "code_in": "OTP in",
  'tell_us_about_yourself': "Tell us about yourself",
};

const BN_TEXT = {
  "recommendedCourses": "সুপারিশকৃত কোর্স",
  "learnNewEveryday": "নতুন প্রতিদিন শিখুন",
  "otherLearnerCourses": "অন্যান্য মাস্টারজি কি শিখছে তা জানুন",
  "verify_your_mobile": "আপনার মোবাইল যাচাই করুন",
  "alert": "সতর্কবাণী",
  "login": "লগ ইন",
  "logout": "লগ আউট",
  "edit_portfolio": "Edit Portfolio",
  "no": "না",
  "yes": "হ্যাঁ",
  "profile_title": "প্রোফাইল",
  "cancel": "বাতিল",
  "take_a_picture": "একটি ছবি নিন",
  "pick_from_gallery": "গ্যালারি থেকে নির্বাচন করুন",
  "ok": "ঠিক আছে",
  "loading": "লোড হচ্ছে…",
  "submit": "জমা দিন",
  "announcements": "ঘোষণা",
  "training": "প্রশিক্ষণ",
  "mandatory_courses": "বাধ্যতামূলক পাঠ্যক্রম",
  "library": "গ্রন্থাগার",
  "analytics": "বিশ্লেষণ",
  "my_certificates": "আমার শংসাপত্",
  "asking_rate_calculator": "আস্কিং রেট ক্যাল্কুলেটার",
  "create_a_session": "সেশান তৈরি করুন",
  "scheduled_sessions": "সেশান শিডিউল করুন",
  "feedback": "প্রতিক্রিয়া",
  "survey": "সমীক্ষা",
  "language": "ভাষা",
  "account_settings": "অ্যাকাউন্ট সেটিংস",
  "FAQs": "বারংবার জিজ্ঞাসিত প্রশ্",
  "contact_us": "যোগাযোগ করুন",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "সব দেখুন",
  "attachFile": "Attach file",
  "start_survey": "সমীক্ষা শুরু করুন",
  "announcement_filters": "ঘোষণা ফিল্টার",
  "write_feedback": "একটি প্রতিক্রিয়া লিখুন",
  "write_an_idea": "একটি ধারণা লিখুন",
  "library_filters": "সংগ্রহ ফিল্টার",
  "notifications": "বিজ্ঞপ্তি",
  "profile": "প্রোফাইল",
  "address": "ঠিকানা",
  "landmark": "ল্যান্ডমার্ক",
  "post_office": "ডাকঘর",
  "city": "শহর",
  "state": "রাজ্য",
  "save_changes": "পরিবর্তনগুলি সেভ করুন",
  "save": "সংরক্ষণ",
  "app_language": "অ্যাপের ভাষা বেছে নিন",
  "content_language": "সূচীপত্রের ভাষা",
  "choose_app_language": "অ্যাপ্লিকেশন ভাষা চয়ন করুন",
  "choose_content_language": "বিষয়বস্তুর ভাষা চয়ন করুন",
  "first_name": "নামের প্রথম অংশ",
  "last_name": "নামের শেষাংশ",
  "date_of_birth": "জন্ম তারিখ",
  "mobile_number": "মোবাইল নম্বর",
  "email_address": "ইমেল",
  "email_address_error": "Email address is invalid",
  "title": "শিরোনাম",
  "topic": "বিষয়",
  "description": "বর্ণনা",
  "select_app_language": "অ্যাপের ভাষা নির্বাচন করুন",
  "language_option": "ভাষার তালিকা থেকে পরে এটি পরিবর্তন করতে পারেন",
  "select_content_language": "বিষয়বস্তুর ভাষা নির্বাচন করুন",
  "update_version_title": "আপডেট উপলব্ধ আছে",
  "update_version_text1":
      "নতুন ভার্সন উপলব্ধ আছে। আপনি কি অ্যাপ আপডেট করতে চান?",
  "update_version_text2": "নতুন ভার্সন উপলব্ধ আছে। দয়া করে অ্যাপ আপডেট করুন।",
  "forgot_pass": "পাসওয়ার্ড ভুলে গেছেন?",
  "photo_alert": "ছবি সেট করুন",
  "take_a_video": "ভিডিও নির্বাচন করুন",
  "pick_a_video": "ভিডিও নির্বাচন করুন",
  "pick_a_file": "ফাইল নির্বাচন করুন",
  "verification": "যাচাই",
  "you_can_change_langauge": "পরে ভাষার তালিকা থেকে এটিকে পরিবর্তন করতে পারেন",
  "submitted": "জমা পড়েছে",
  "choose_language": "ভাষা বেছে নিন",
  "update_profile": "Update My Space",
  "gender": "লিঙ্গ",
  "male": "পুরুষ",
  "female": "মহিলা",
  "faqTitle1": "আমি আমার চ্যাপ্টার / মডিউল খুঁজে পাচ্ছি না",
  "faqTitle2": "আমি লাইভ ক্লাসে ঢুকতে পারছি না",
  "faqTitle3": "আমি কি অ্যাপে লগইন করার পর বিষয়ের ভাষা পালটাতে / বদলাতে পারি?",
  "faqTitle4":
      "নিজের পছন্দের ভাষা বেছে নেওয়ার পর, প্রতিবার অ্যাপ খোলার সময় আমাকে কি ভাষা পালটাতে হবে?",
  "faqTitle5":
      "যে সমস্ত ট্রেনিং / প্রশিক্ষণ আগের অ্যাপে শেষ করা হয়ে গেছে সেগুলির কি হবে? ",
  "faqTitle6": "আমরা কি অ্যাপের থেকে বিষয় বস্তু নামাতে / ডাউনলোড করতে পারি?",
  "faqTitle7":
      "আস্কিং রেট ক্যালকুলেটারে, কিছু ইউজারের সোমবার বা মঙ্গলবার বার বিশেষ কোনো দিনে সাপ্তাহিক ছুটি দেখায় / থাকে। সেটা কি করে ট্র্যাক করা যায়?",
  "faq2": "A. প্রশিক্ষণের মধ্যে থাকা লাইভ ক্লাস। -\nআপনি যদি একটা বিশেষ প্রশিক্ষণের সমস্ত লাইভ ক্লাস দেখতে চান, তাহলে প্রশিক্ষণে যে লিঙ্ক দেওয়া আছে তা ক্লিক করুন, সেখান থেকে যে লাইভ ক্লাস ট্যাব খুলবে, তাতে ক্লিক করুন আর তাহলেই আপনি উপলব্ধ লাইভ ক্লাসে যোগ দিতে পারেন \n\n"
      "B. মডিউলে থাকা লাইভ ক্লাস। -\nযদি আপনি একটা বিশেষ মডিউলের লাইভ ক্লাস দেখতে চান, তাহলে প্রশিক্ষণে ক্লিক করুন, তাহলে আপনি মডিউলের একটা সূচি পেয়ে যাবেন। সেই মডিউলের মধ্যে দিয়ে গেলে আপনি সমস্ত প্রশিক্ষণের সূচি পেয়ে যাবেন। সেখান থেকে আপনি উপলব্ধ লাইভ ক্লাসে যোগ দিতে পারেন।\n\n"
      "C. ঘোষণা করা লাইভ ক্লাস / ঘোষণার মধ্যে থাকা লাইভ ক্লাস -\nযদি আপনি হাইলাইটে থাকা লাইভ ক্লাসে যোগ দিতে চান, তাহলে হাইলাইটে ক্লিক করুন। যে সমস্ত কর্মসূচি দেওয়া আছে তার মধ্যে দিয়ে যান। সেখানে উপলব্ধ লাইভ ক্লাসে আপনি যোগ দিতে পারেন।\n\n"
      "D. যদি লাইভ সেশান দেখতে না পান। –\nযদি আপনি লাইভ সেশান দেখতে না পান, তাহলে আপনার ব্রাউজার উইন্ডোর ওপরের ডানদিকের ব্লকটা চেক করুন। সেই ব্লকটায় ক্লিক করুন আর অ্যালাউতে চেক করুন, এইভাবে - https://swayam.pvmi.in/img/step.jpg  ",
  "faq1":
      "প্রশিক্ষণ থেকে লিঙ্কটা ক্লিক করুন, সেখানে সমস্ত প্রশিক্ষণের সূচি পেয়ে যাবেন। আপনার বিশেষ প্রশিক্ষণে ক্লিক করুন সেখান থেকে আপনি সব মডিউল দেখতে পাবেন।",
  "faq3":
      "হ্যাঁ, আপনাকে মেনুর ল্যাংগুয়েজ অপশানে যেতে হবে আর সেখান থেকে আপনি অ্যাপ এবং বিষয়ের ভাষা বেছে নিতে পারবেন।",
  "faq4":
      "না, ইউজার কে কেবল একবারই পছন্দের ভাষা বেছে নিতে হবে। সেটা অ্যাপে সেভ করা থাকবে। তবে ইউজার আবার সেই ভাষা নিজের ইচ্ছে মত পালটে নিতে পারবেন।",
  "faq5":
      "সেই সমস্ত তথ্য রিপোর্টে দেওয়া থাকবে, তবে অ্যাপে সেগুলো দেখাতে কিছুটা সময় লাগতে পারে কারণ তা ব্যাক – এন্ড থেকে করতে হবে।",
  "faq6": "না, নামানোর / ডাউনলোড করার সুবিধা অ্যাপে পাওয়া যাবে না।",
  "faq7":
      "সাধারণ ভাবে ধরার জন্য আমরা রবিবার কে সাপ্তাহিক ছুটির দিন হিসেবে ধরে রেখেছি আর সপ্তায় ছ – দিন কে কাজ করার দিনের হিসেবের মধ্যে ধরছি। তা ছাড়া আন্দাজ কতদিন কাজ হবে তাও দেওয়া থাকবে",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "আইডিয়া ফ্যাকট্রি",
  "Create_Live_Class": "লাইভ ক্লাস তৈরি করুন",
  "Schedule_Now": "সময় নির্ধারণ করুন",
  "Create_a_Session": "সেশান শুরু করুন",
  "Select_Title": "টাইটেল লিখুন",
  "Select_Date": "তারিখ বাছুন",
  "Invite_learners": "ছাত্রদের আমন্ত্রণ জানান",
  "Members_added": "মেম্বার যোগ করুন",
  "Publish_Now": "পাবলিশ করুন",
  "Save_as_draft": "রাফট বানিয়ে রাখুন",
  "Schedules_Sessions": "সেশানের সময় নির্ধারণ করুন",
  "Upcoming_Sessions": "পরবর্তি সেশান",
  "Draft": "ড্রাফট",
  "What_to_expect": "কি পাওয়া যাবে",
  "Start_date": "শুরুর তারিখ",
  "End_date": "শেষের তারিখ",
  "Modules_included": "কি কি মডিউল আছে",
  "List_of_modules": "মডিউলের তালিকা",
  "Content": "সূচীপত্",
  "Scorm": "স্কর্ম",
  "Live_sessions": "লাইভ সেশান",
  "Videos": "ভিডিও",
  "Notes": "নোট",
  "Assignment": "অয়াসাইন্মেন্",
  "Define_your_self": "নিজের লক্ষ নির্ধারণ করুন এবং আরো বেশী উন্নতি করুন",
  "Certification": "শংসাপত্র",
  "My_Analytics": "আমার অ্যানালিটিকস",
  "Team_Analytics": "টিম অ্যানালিটিকস",
  "KPI_Analytics": "কেপিআই অ্যানালিটিকস",
  "Course_level_Analysis": "কোর্সের স্তরের বিশ্লেষণ",
  "Module_level_Analysis": "মডিউলের স্তরের বিশ্লেষণ",
  "Leaderboard": "লিডারবোর্",
  "Switch_to_modules": "মডিউলে ফিরে যান",
  "Switch_to_leaderboard": "লিডারবোর্ডে ফিরে যান",
  "Completed": "শেষ হয়ে গেছে",
  "Score": "কোর",
  "Course_name": "কোর্সের নাম",
  "KPIs_assigned": "বরাদ্দ করা কেপিআই",
  "Monthly_performance": "মাসিক প্রদর্শন",
  "My_certificates": "আমার শংসাপত্",
  "Your_medals": "আপনার মেডেল",
  "Certificates": "শংসাপত্",
  "Set_your_goals":
      "নিচের ক্যাল্কুলেটারে নিজের লক্ষ সেট করুন এবং দেখুন কিভাবে এগোতে হবে সেই লক্ষে পৌঁছতে",
  "Select_your_goal": "লক্ষ নির্ধারণ করুন",
  "Calculate_now": "হিসেব করুন",
  "Billed_outlets": "যে সমস্ত আউটলেট কে বিল করা হয়েছে",
  "Targeted_outlets": "নির্ধারণ করা আউটলেট",
  "Target": "লক্ষ্য",
  "Currently_achieved": "এই মুহূর্তের অবস্থান",
  "Total_MSS_Points": "মোট এমএসএস পয়েন্",
  "Calculated_asking_rate": "হিসেব করা আস্কিং রেট",
  "Manage_your_everyday":
      "প্রতিদিনের অবস্থান হিসেব করা যাতে আরো বড় লক্ষে পৌঁছনো যায়",
  "For_next": "এরপরের জন্",
  "Days": "দিন",
  "Details": "ডিটেল",
  'time': "সময়",
  'duration': "সময়কাল",
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/ create account to continue',
  'phone_number': 'Phone number',
  'continue': 'continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and condition & privacy policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'verification_title': "Enter OTP that sent to",
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  "resend": "Re-send",
  "code_in": "OTP in",
  'let_us_about_your_self': 'Tell us about yourself'
};

const HI_TEXT = {
  "recommendedCourses": "अनुशंसित पाठ्यक्रम",
  "learnNewEveryday": "हर रोज नया सीखें",
  "otherLearnerCourses": "जानें कि दूसरे MasterG क्या सीख रहे हैं",
  "alert": "अलर्ट",
  "login": "लॉग इन करें",
  "logout": "लॉग आउट",
  "edit_portfolio": "पोर्टफोलियो संपादित करें",
  "myassessments": "मेरे आकलन",
  "no": "नहीं",
  "yes": "हाँ",
  "profile_title": "प्रोफाइल",
  "recent_activity": "हाल की गतिविधि",
  "cancel": "रद्द करें",
  "take_a_picture": "तस्वीर लें",
  "pick_from_gallery": "गैलरी से चुनें",
  "ok": "ठीक है",
  "loading": "लोड हो रहा है..",
  "submit": "प्रस्तुत करें",
  "announcements": "घोषणाओं",
  "training": "प्रशिक्षण",
  "mandatory_courses": "अनिवार्य पाठ्यक्रम",
  "library": "लाइब्रेरी",
  "analytics": "अनालिटिक्स",
  "my_certificates": "मेरे प्रमाण पत्र",
  "asking_rate_calculator": "आस्किंग रेट कैलकुलेटर",
  "create_a_session": "सत्र बनाएँ",
  "scheduled_sessions": "शेड्यूल्ड सत्र",
  "feedback": "फ़ीडबैक",
  "survey": "सर्वेक्षण",
  "language": "भाषा",
  "attachFile": "Attach file",
  "account_settings": "अकाउंट (खाता) सेटिंग",
  "FAQs": "सामान्य प्रश्न",
  "contact_us": "संपर्क करें",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "सभी देखें",
  "start_survey": "सर्वेक्षण शुरू करें",
  "announcement_filters": "घोषणा फ़िल्टर",
  "write_feedback": "फ़ीडबैक लिखें",
  "write_an_idea": "आइडिया लिखें",
  "library_filters": "लाइब्रेरी फिल्टर",
  "notifications": "सूचनाएं",
  "profile": "प्रोफाइल",
  "address": "पता",
  "landmark": "लैन्ड मार्क",
  "post_office": "डाक घर",
  "city": "शहर",
  "state": "राज्य",
  "save_changes": "बदलावओं को सहेजें",
  "save": "सहेजें",
  "app_language": "ऐप की भाषा",
  "content_language": "विषय की भाषा",
  "choose_app_language": "अपनी ऐप की भाषा चुने ",
  "choose_content_language": "चुनें विषय की भाषा",
  "first_name": "नाम",
  "last_name": "उपनाम",
  "date_of_birth": "जन्म की तारीख",
  "mobile_number": "मोबाइल नंबर",
  "email_address": "ईमेल पता",
  "myclasses": "मेरी कक्षा",
  "email_address_error": "ईमेल पता अवैध है",
  "byInstructorName": "प्रशिक्षक के नाम से",
  "myassignments": "मेरे असाइनमेंट",
  "title": "शीर्षक",
  "topic": "विषय",
  "description": "विवरण",
  "select_app_language": "चुनें ऐप की भाषा",
  "language_option": "आप इसे बाद में भी भाषा विकल्प से बदल सकते हैं",
  "select_content_language": "चुनें विषय की भाषा",
  "update_version_title": "अपडेट उपलब्ध है",
  "update_version_text1":
      "एक नया संस्करण उपलब्ध है। क्या आप ऐप को अपडेट करना चाहेंगे?",
  "update_version_text2": "एक नया संस्करण उपलब्ध है। कृपया ऐप को अपडेट करें।",
  "forgot_pass": "पासवर्ड भूल गया हूँ",
  "photo_alert": "एक तस्वीर सेट करें",
  "take_a_video": "एक वीडियो ले",
  "pick_a_video": "एक वीडियो चुनें",
  "pick_a_file": "एक फ़ाइल चुनें",
  "verification": "वेरिफ़ाय करें",
  "you_can_change_langauge": "आप इसे बाद में भाषा विकल्प से बदल सकते हैं",
  "submitted": "सबमिट",
  "choose_language": "भाषा चुनें",
  "update_profile": "प्रोफ़ाइल अपडेट करें",
  "gender": "लिंग",
  "male": "पुरुष",
  "female": "महिला",
  "faqTitle1": "मुझे अध्यायों / मॉड्यूल का उपयोग करने में दिक्कत हो रही है।",
  "faqTitle2": "मुझे लाइव क्लास में भाग लेने में दिक्कत हो रही है।",
  "faqTitle3":
      "क्या मैं ऐप में लॉग इन करने के बाद बीच में कंटेंट की भाषा बदल सकता हूं?",
  "faqTitle4":
      "एक बार भाषा को चयन करने के बाद, क्या हर बार ऐप खोलने पर मुझे भाषा की चयन करना है?",
  "faqTitle5":
      "उन प्रशिक्षणों का क्या होगा जो पहले से ही पिछले ऐप में पूरी हो चुकी हैं?",
  "faqTitle6": "क्या हम एप से कंटेंट डाउनलोड कर सकते हैं?",
  "faqTitle7":
      "आस्किंग रेट कैलकुलेटर में, कुछ उपयोगकर्ताओं का सोमवार / मंगलवार को वीक्ली आफ़ है। हम इसे कैसे ट्रैक करते हैं?",
  "faq2": "A. ट्रैनिंग में लाइव क्लास -\nयदि आप सभी लाइव कक्षाओं को विशिष्ट प्रशिक्षण यादी में देखना चाहते हैं, तो ट्रेनिंग के लिंक का अनुसरण करें, लाइव क्लास टैब पर क्लिक करें। आप उपलब्ध लाइव कक्षाओं में शामिल हो सकते हैं।.\n\n"
      "B. मॉड्यूल में लाइव क्लास -\nयदि आप एक मॉड्यूल संबंधी लाइव कक्षाओं को देखना चाहते हैं, तो प्रशिक्षण पर क्लिक करें और आप सभी मॉड्यूल की सूची में आ जाएंगे। नेविगेट कर के सभी मॉड्यूल जान लीजिये और प्रशिक्षणों की सूची देखेंगे। आप उपलब्ध लाइव क्लास में शामिल हो सकते हैं।\n\n"
      "C. घोषणा में लाइव क्लास -\nयदि आप हाइलाइट्स संबंधी लाइव क्लासेस देखना चाहते हैं, तो केवल हाइलाइट्स पर क्लिक करें। सूचीबद्ध गतिविधियों के द्वारा नेविगेट करें। फिर आप उपलब्ध लाइव कक्षाओं में शामिल हो सकते हैं।\n\n"
      "D. लाइव सत्र देखने में दिक्खत हो रही है –\nयदि आपको लाइव सत्र देखने में दिक्खत हो रही है, तो शीर्ष दाएं ब्राउज़र विंडो में ब्लॉक की जांच करें। ब्लॉक पर क्लिक करें और चेक की अनुमति दें। फिर छवि: https://swayam.pvmi.in/img/step.jpg ",
  "faq1":
      "ट्रैनिंग के लिंक का अनुसरण करें, आपको सभी प्रशिक्षणों की सूची मिल जाएगी। अपेक्षित प्रशिक्षण पर क्लिक करें और आप नेविगेट कर के सभी मॉड्यूल के जान सकते हैं।",
  "faq3":
      "हां, मेन्यू में लैंग्वेज ऑप्शन पर जाएं और वहां ऐप के साथ-साथ कंटेंट का भी भाषा चुन सकते हैं।",
  "faq4":
      "नहीं, केवल एक बार उपयोगकर्ता को भाषा का चयन करना होगा। यह ऐप में सेव रहेगा। लेकिन उपयोगकर्ता भाषा को बदलने का विकल्प चुन सकता है।",
  "faq5":
      "यह रिपोर्टों में पूरा हो जाएगा, लेकिन इसे ऐप पर दिखाने के लिए कुछ समय लग सकता है क्योंकि इसे बैकएंड में जाना है।",
  "faq6": "नहीं, एप में डाउनलोड का ऑप्शन उपलब्ध नहीं है।",
  "faq7":
      "एक सामान्य मानक के रूप में हमने रविवार को वीक्ली आफ़ और सप्ताह में 6 दिन मानव-दिवस की गणना के लिए रखी है। अनुमानित मानव-दिन के उपलब्धता का भी उल्लेख रहेगा।",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "आइडिया फैक्ट्री",
  "Create_Live_Class": "लाइव क्लास बनाएं",
  "Schedule_Now": "अब शेड्यूल करें",
  "Create_a_Session": "सत्र बनाएँ",
  "Select_Title": "शीर्षक का चयन करें",
  "Select_Date": "तारीख़ चुनें",
  "Invite_learners": "शिक्षार्थियों को आमंत्रित करें",
  "Members_added": "सदस्यों को जोड़ा गया",
  "Publish_Now": "अब प्रकाशित करें",
  "Save_as_draft": "रारूप के रूप में सेव करें",
  "Schedules_Sessions": "शेड्यूल्ड सत्",
  "Upcoming_Sessions": "आगामी सत्",
  "Draft": "प्रारूप",
  "What_to_expect": "अपेक्षा क्या करें",
  "Start_date": "शुरु होने की तिथि",
  "End_date": "अंतिम तिथि",
  "Modules_included": "मॉड्यूल्स शामिल किये गये",
  "List_of_modules": "मॉड्यूल्स की सूची",
  "Content": "सामग्री",
  "Scorm": "Scorm",
  "Live_sessions": "लाइव सत्र",
  "Videos": "वीडियो",
  "Notes": "टिप्पणियाँ",
  "Assignment": "असाइनमेंट",
  "Define_your_self":
      "अपने स्वलक्ष्यों को परिभाषित करें और अपने सुधार को बढ़ावा दें",
  "Certification": "प्रमाणीकरण",
  "My_Analytics": "मेरी अनालिटिक्स",
  "Team_Analytics": "टीम अनालिटिक्स",
  "KPI_Analytics": "के पी आई अनालिटिक्स",
  "Course_level_Analysis": "कोर्स स्तर पर विश्लेषण",
  "Module_level_Analysis": "मॉड्यूल स्तर पर विश्लेषण",
  "Leaderboard": "ಲೀಡರ್‌ಬೋರ್ಡ್",
  "Switch_to_modules": "ಮಾಡ್ಯೂಲ್‌ಗಳಿಗೆ ಬದಲಿಸಿ",
  "Switch_to_leaderboard": "ಲೀಡರ್‌ಬೋರ್ಡ್‌ಗೆ ಬದಲಿಸಿ",
  "Completed": "लीडरबोर्ड",
  "Score": "अंक",
  "Course_name": "कोर्स का नाम",
  "KPIs_assigned": "केपीआई को सौंपा गया",
  "Monthly_performance": "मासिक निष्पादन",
  "My_certificates": "मेरे प्रमाण पत्र",
  "Your_medals": "आपके पदक",
  "Certificates": "प्रमाण पत्र",
  "Set_your_goals":
      "नीचे दिए गए कैलकुलेटर में अपने लक्ष्यों को निर्धारित करें और लक्ष्य को पूरा करने के लिए आवश्यक दर को ट्रैक करें",
  "Select_your_goal": "अपना लक्ष्य चुनें",
  "Calculate_now": "अब गणना करें",
  "Billed_outlets": "बिलों के आउटलेट",
  "Targeted_outlets": "लक्षित आउटलेट्स",
  "Target": "लक्ष्य",
  "Currently_achieved": "वर्तमान में उपलब्धी",
  "Total_MSS_Points": "कुल एमएसएस अंक",
  "Calculated_asking_rate": "गणना की गयी आस्किंग रेट",
  "Manage_your_everyday_to_achieve_bigger_results":
      "बड़े परिणाम प्राप्त करने के लिए अपने हर दिन को संभालिये",
  "For_next": "अगले के लिए",
  "Days": "दिन",
  "Details": "विवरण",
  'time': "समय",
  'duration': "समयांतराल",
  'verify_your_mobile': "मोबाइल सत्यापित करें",
  'Lets_start_your_journey': 'आइए अपनी सीखने की यात्रा शुरू करें',
  'choose_your_app_language': 'अपने ऐप की भाषा चुनें',
  'giving_your_creativity': 'अपनी रचनात्मकता को एक नया रास्ता दें',
  'login_create_account': 'जारी रखने के लिए लॉगिन/खाता बनाएं',
  'phone_number': 'फ़ोन नंबर',
  'your_mobile_number': 'आपका मोबाइल नम्बर',
  'continue': 'जारी रखें',
  'by_clicking_continue': 'जारी रखें क्लिक करके, मैं नियम और',
  'by_clicking_continue_underline': ' शर्त और गोपनीयता नीति स्वीकार करता हूं',
  'having_trouble':
      'लॉगिन करने में समस्या आ रही है? हमसे संपर्क करें +91 7428096480',
  "resend": "पुन: भेजें",
  "code_in": "ओटीपी पुनः भेजें",
  'change_phone_number': 'फ़ोन नंबर बदलें',
  'select_categories': 'श्रेणियाँ चुनें',
  'select_atleast_category': 'कम से कम 1 श्रेणी चुनें',
  'verification_title': 'भेजा गया ओटीपी दर्ज करें',
  'enter_full_name': 'पूरा नाम दर्ज करें',
  'choose_image': 'छवि चुनें',
  'choose_image_description':
      'अपना प्रोफ़ाइल चित्र अपलोड करने के लिए गैलरी या कैमरे से चुनें',
  'gallery': 'गैलरी',
  'camera': 'कैमरे',
  'choose_profile_image': 'प्रोफ़ाइल चित्र चुनें',
  'change_profile_image': 'प्रोफ़ाइल चित्र बदलें',
  'phone_already_exists': 'यह फ़ोन नंबर पहले से मौजूद है',
  'use_another_phone': 'अन्य फ़ोन नंबर का उपयोग करें',
  'choose_your_interests': 'अपनी रुचि चुनें',
  'select_aleast_six_categories': 'कम से कम 1 श्रेणि चुनें',
  'create_post': 'पोस्ट बनाएं',
  'create_reels': 'रीलीज बनाएं',
  'like': 'पसंद करें',
  'share': 'शेयर करें',
  'comment': 'टिप्पणी करें',
  'email': 'ईमेल',
  'phone': 'फ़ोन',
  'reels': 'Reels',
  'views': 'देखे गए',
  'ghome': 'Gहोम',
  'gschool': 'Gस्कूल',
  'greels': 'Gरील्स',
  'gcarvaan': 'Gकारवां',
  'write_your_post': 'Write your post',
  'add_more': 'Add more',
  'tell_us_about_yourself': 'आप अपने बारे में बताओ',
  'category_not_found': "श्रेणी नहीं मिली!",
  'there_are_no_recent_activity': 'वहां कोई वर्तमान गतिविधि नहीं है!!',
  'apni_padhai_jaari_rakein': 'अपनी पढाई जारी रखे',
  'my_quiz': 'मेरी प्रश्नोत्तरी',
  'my_courses': 'मेरे पाठ्यक्रम',
  'completed': 'पूरा किया हुआ'
};

const KN_TEXT = {
  "alert": "ಎಚ್ಚರ",
  "login": "ಲಾಗಿನ್ ಮಾಡಿ",
  "logout": "ಲಾಗೌಟ್ ಮಾಡಿ",
  "edit_portfolio": "Edit Portfolio",
  "no": "ಬೇಡ",
  "yes": "ಬೇಕು",
  "profile_title": "ಪ್ರೊಫೈಲ್",
  "cancel": "ರದ್ದುಗೊಳಿಸಿ",
  "take_a_picture": "ಚಿತ್ರ ತೆಗೆದುಕೊಳ್ಳಿ",
  "pick_from_gallery": "ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆ ಮಾಡಿ",
  "ok": "ಓಕೆ",
  "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "submit": "ಸಲ್ಲಿಸಿ",
  "announcements": "ಪ್ರಕಟಣೆಗಳು",
  "training": "ತರಬೇತಿಗಳು",
  "mandatory_courses": "ಕಡ್ಡಾಯ ಕೋರ್ಸ್‌ಗಳು",
  "library": "ಗ್ರಂಥಾಲಯ",
  "analytics": "ವಿಶ್ಲೇಷಣೆ",
  "attachFile": "Attach file",
  "my_certificates": "ನನ್ನ ಪ್ರಮಾಣಪತ್ರಗಳು",
  "asking_rate_calculator": "ಆಸ್ಕಿಂಗ್ ರೇಟ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
  "create_a_session": "ತರಗತಿ ರಚಿಸಿ",
  "scheduled_sessions": "ನಿಗದಿತ ತರಗತಿಗಳು",
  "feedback": "ಫೀಡ್ ಬ್ಯಾಕ್",
  "survey": "ಸಮೀಕ್ಷೆ",
  "language": "ಭಾಷೆ",
  "account_settings": "ಖಾತೆಯ ಸೆಟ್ಟಿ0ಗ್ಗಳು",
  "FAQs": "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು",
  "contact_us": "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "ಎಲ್ಲವನ್ನು ವೀಕ್ಷಿಸಿ",
  "start_survey": "ಸಮೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
  "announcement_filters": "ಪ್ರಕಟಣೆ ಫಿಲ್ಟರ್ಗಳು",
  "write_feedback": "ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಬರೆಯಿರಿ",
  "write_an_idea": "ಕಲ್ಪನೆಯನ್ನು ಬರೆಯಿರಿ",
  "library_filters": "ಲೈಬ್ರರಿ ಫಿಲ್ಟರ್ಗಳು",
  "notifications": "ಸೂಚನೆಗಳು",
  "profile": "ಪ್ರೊಫೈಲ್",
  "address": "ವಿಳಾಸ",
  "landmark": "ಲ್ಯಾಂಡ್ ಮಾರ್ಕ್",
  "post_office": "ಅಂಚೆ ಕಚೇರಿ",
  "city": "ನಗರ",
  "state": "ರಾಜ್ಯ",
  "save_changes": "ಬದಲಾವಣೆಗಳನ್ನು ಸೇವ್ ಮಾಡಿ",
  "save": "ಸೇವ್ ಮಾಡಿ",
  "app_language": "ಆಪ್ ಭಾಷೆ",
  "content_language": "ವಿಷಯದ ಭಾಷೆ",
  "choose_app_language": "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
  "choose_content_language": "ವಿಷಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
  "first_name": "ಮೊದಲ ಹೆಸರು",
  "last_name": "ಕೊನೆಯ ಹೆಸರು",
  "date_of_birth": "ಜನ್ಮ ದಿನಾಂಕ",
  "mobile_number": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  "email_address": "ಈ-ಮೇಲ್ ವಿಳಾಸ",
  "email_address_error": "Email address is invalid",
  "title": "ಶೀರ್ಷಿಕೆ",
  "topic": "ವಿಷಯ",
  "description": "ವಿವರಣೆ",
  "select_app_language": "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
  "language_option": "ಭಾಷೆ ಆಯ್ಕೆಯಿ೦ದ ನೀವು ಇದನ್ನು ನ0ತರ ಬದಲಾಯಿಸಿಕೊಳ್ಳಬಹುದು",
  "select_content_language": "ವಿಷಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "update_version_title": "ಅಪ್ಡೇಟ್ ಲಭ್ಯವಿದೆ",
  "update_version_text1":
      "ಹೊಸ ಆವೃತ್ತಿ ಲಭ್ಯವಿದೆ. ನೀವು ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ನವೀಕರಿಸಲು ಬಯಸುವಿರಾ?",
  "update_version_text2": "ಹೊಸ ಆವೃತ್ತಿ ಲಭ್ಯವಿದೆ. ದಯವಿಟ್ಟು ಅಪ್ಲಿಕೇಶನ್ ನವೀಕರಿಸಿ.",
  "forgot_pass": "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿದ್ದೇನೆ",
  "photo_alert": "ಫೋಟೋ ಸೆಟ್ ಮಾಡಿ",
  "take_a_video": "ವೀಡಿಯೊ ತೆಗೆದುಕೊಳ್",
  "pick_a_video": "ವೀಡಿಯೊವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "pick_a_file": "ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ",
  "verification": "ವೆರಿಫಿಕೇಶನ್",
  "you_can_change_langauge": "ನೀವು ನಂತರ ಭಾಷೆಯ ಆಯ್ಕೆಯಿಂದ ಬದಲಾಯಿಸಬಹುದು",
  "submitted": "ಸಬ್ಮಿಟ್",
  "choose_language": "ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
  "update_profile": "Update My Space",
  "gender": "ಲಿಂಗ",
  "male": "ಪುರುಷ",
  "female": "ಹೆಣ್ಣು",
  "faqTitle1":
      "ಅಧ್ಯಾಯಗಳನ್ನು ಅಥವಾ ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ತೆರಯಲು ನನಗೆ ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ.",
  "faqTitle2": "ನನಗೆ ಲೈವ್ ತರಗತಿಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ.",
  "faqTitle3":
      "ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ಲಾಗ್ ಇನ್ ಮಾಡಿದ ನಂತರ ನಾನು ವಿಷಯದ ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಬಹುದೇ?",
  "faqTitle4":
      "ನಾನು ಯಾವುದೇ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿದ ನಂತರ, ನಾನು ಆಪ್ ತೆರೆದಾಗಲೆಲ್ಲಾ ಅದನ್ನು ಆಯ್ಕೆ ಮಾಡಬೇಕೇ?",
  "faqTitle5": "ಹಿಂದಿನ ಅಪ್ನಲ್ಲಿ ಈಗಾಗಲೇ ಪೂರ್ಣಗೊಂಡಿರುವ ತರಬೇತಿಗಳಿಗೆ ಏನಾಗುತ್ತದೆ? ",
  "faqTitle6": "ನಾವು ಆಪ್ನಿಂದ ವಿಷಯವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಬಹುದೇ?",
  "faqTitle7":
      "ಆಸ್ಕಿಂಗ್ ರೇಟ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಅನ್ನು ಕೇಳುವಾಗ, ಕೆಲವು ಬಳಕೆದಾರರ ವಾರದ ರಜೆಗಳು ಸೋಮವಾರ / ಮಂಗಳವಾರ, ಹೀಗೆ ವಾರಕ್ಕೊಮ್ಮೆ ಇರುತ್ತದೆ. ನಾವು ಅದನ್ನು ಹೇಗೆ ಟ್ರ್ಯಾಕ್ ಮಾಡುಬಹುದು?",
  "faq2": "A. ತರಬೇತಿಯಲ್ಲಿ ಲೈವ್ ತರಗತಿ -\nನಿರ್ದಿಷ್ಟ ತರಬೇತಿಯಲ್ಲಿ ಎಲ್ಲಾ ಲೈವ್ ತರಗತಿಗಳನ್ನು ನೀವು ನೋಡಲು ಬಯಸಿದರೆ, ಆ ತರಬೇತಿಯ ಲಿಂಕ್‌ಅನ್ನು ಫಾಲೋ ಮಾಡಿ, ಅಲ್ಲಿರುವ ಲೈವ್ ಕ್ಲಾಸ್ ಟ್ಯಾಬಿನ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ಲಭ್ಯವಿರುವ ಲೈವ್ ತರಗತಿಗಳಿಗೆ ನೀವು ಸೇರಬಹುದು.\n\n"
      "B. ಮಾಡ್ಯೂಲ್ನಲ್ಲಿ ಲೈವ್ ತರಗತಿ -\nನೀವು ನಿರ್ದಿಷ್ಟವಾದ ಮಾಡ್ಯೂಲ್ಲಿನ ಲೈವ್ ತರಗತಿಗಳನ್ನು ನೋಡಲು ಬಯಸಿದರೆ, ಅಲ್ಲಿರುವ ತರಬೇತಿಯ ಲಿಂಕ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿದರೆ ಎಲ್ಲಾ ರೀತಿಯ ಮಾಡ್ಯೂಲ್‌ಗಳ ಪಟ್ಟಿ ಸಿಗುವುದು. ಅಲ್ಲಿರುವ ಮಾಡ್ಯೂಲ್ ಮೂಲಕ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿದರೆ ನಿಮಗೆ ಎಲ್ಲಾ ತರಬೇತಿಗಳ ಪಟ್ಟಿಯು ಕಾಣುವುದು. ನಂತರ ನೀವು ಲಭ್ಯವಿರುವ ಲೈವ್ ವರ್ಗಕ್ಕೆ ಸೇರಬಹುದು.\n\n"
      "C. ಲೈವ್ ತರಗತಿಯ ಪ್ರಕಟಣೆ-\nನೀವು ನಿರ್ದಿಷ್ಟವಾದ ಲೈವ್ ತರಗತಿಯ ಮುಖ್ಯಾಂಶಗಳನ್ನು ನೋಡಲು ಬಯಸಿದರೆ, ಮುಖ್ಯಾಂಶಗಳ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ. ಅಲ್ಲಿ ಕಾಣಸಿಗುವ ಚಟುವಟಿಕೆಗಳ ಪಟ್ಟಿಯನ್ನು ನ್ಯಾವಿಗೇಟ್ ಮಾಡುವ ಮೂಲಕ ನಿಮಗೆ ಲಭ್ಯವಿರುವ ಲೈವ್ ತರಗತಿಯನ್ನು ಸೇರಬಹುದು.\n\n"
      "D. ಲೈವ್ ಸೆಷನ್ ವೀಕ್ಷಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. –\nನಿಮಗೆ ಲೈವ್ ಸೆಷನ್ ವೀಕ್ಷಿಸಲು ಸಾಧ್ಯವಾಗದಿದ್ದರೆ, ಮೇಲೆ ಬಲ ಬ್ರೌಸರ್ ವಿಂಡೋದಲ್ಲಿ ಬ್ಲಾಕ್ಕನ್ನು ಪರಿಶೀಲಿಸಿ ಅಲ್ಲಿ ಅನುಮತಿಯನ್ನು ನೀಡಿ. ನಂತರ ಚಿತ್ರ: https://swayam.pvmi.in/img/step.jpg ",
  "faq1":
      "ತರಬೇತಿಯ ಲಿಂಕ್ಅನ್ನು ಅನುಸರಿಸಿ, ಅಲ್ಲಿ ನೀವು ಎಲ್ಲಾ ತರಬೇತಿಗಳ ಪಟ್ಟಿಯನ್ನು ಕಾಣಬಹುದು. ನಿಮಗೆ ಬೇಕಾಗಿರುವ ನಿರ್ದಿಷ್ಟ ತರಬೇತಿಯ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ ಮತ್ತು ನೀವು ಎಲ್ಲಾ ಮಾಡ್ಯೂಲ್‌ಗಳನ್ನು ತೆರೆಯಬಹುದು.",
  "faq3":
      "ಹೌದು, ಮೆನುವಿನಲ್ಲಿರುವ ಭಾಷಾ ಆಯ್ಕೆಗೆ ಹೋಗಿ ಮತ್ತು ಅಲ್ಲಿ ನೀವು ಆಪ್ ಮತ್ತು ವಿಷಯದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಬಹುದು.",
  "faq4":
      "ಇಲ್ಲ, ಒಮ್ಮೆ ಮಾತ್ರ ಬಳಕೆದಾರರು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಬೇಕಾಗುತ್ತದೆ. ಇದು ಆಪ್ನಲ್ಲಿ ಸೇವ್ ಮಾಡಲಾಗಿರುತ್ತದೆ. ಆದರೆ ಬಳಕೆದಾರರು ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸುವ ಆಯ್ಕೆಯನ್ನು ಮಾಡಬಹುದು.",
  "faq5":
      "ವರದಿಗಳಲ್ಲಿ ಪೂರ್ಣಗೊಂಡ ಬಗ್ಗೆ ಮಾಹಿತಿ ಇರುತ್ತದೆ. ಆದರೆ ಅದನ್ನು ಆಪ್ನಲ್ಲಿ ತೋರಿಸಲು, ಬ್ಯಾಕೆಂಡ್‌ನಲ್ಲಿ ಇದನ್ನು ಮಾಡಬೇಕಾಗಿರುವುದರಿಂದ ಸ್ವಲ್ಪ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಬಹುದು.",
  "faq6": "ಇಲ್ಲ, ಡೌನ್‌ಲೋಡ್ ಆಯ್ಕೆ ಆಪ್ನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ.",
  "faq7":
      "ಸಾಮಾನ್ಯವಾಗಿ ನಾವು ಭಾನುವಾರದಂದು ವಾರದ ರಜೆ ನೀಡುತ್ತೇವೆ. ಮಾನವ-ದಿನಗಳ ಲೆಕ್ಕಾಚಾರಕ್ಕೆ ವಾರದಲ್ಲಿ 6 ದಿನಗಳನ್ನು ಪರಿಗಣಿಸುತ್ತೇವೆ.  ಲಭ್ಯವಿರುವ ಅಂದಾಜು ಮಾನವ ದಿನಗಳನ್ನು ಕೂಡಾ ಉಲ್ಲೇಖಿಸಲಾಗಿದೆ. ",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "ಐಡಿಯಾ ಫ್ಯಾಕ್ಟರಿ",
  "Create_Live_Class": "ಲೈವ್ ಕ್ಲಾಸ್ ರಚಿಸಿ",
  "Schedule_Now": "ವೇಳಾಪಟ್ಟಿ ರಚಿಸಿಕೊಳ್ಳಿರಿ",
  "Create_a_Session": "ತರಗತಿ ರಚಿಸಿ",
  "Select_Title": "ಶೀರ್ಷಿಕೆ ಆಯ್ಕೆಮಾಡಿ",
  "Select_Date": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "Invite_learners": "ಕಲಿಯುವವರನ್ನು ಆಹ್ವಾನಿಸಿ",
  "Members_added": "ಸದಸ್ಯರನ್ನು ಸೇರಿಸಲಾಗಿದೆ",
  "Publish_Now": "ಈಗ ಪ್ರಕಟಿಸಿ",
  "Save_as_draft": "ಕರಡು ಉಳಿಸಿ",
  "Schedules_Sessions": "ನಿಗದಿತ ತರಗತಿಗಳು",
  "Upcoming_Sessions": "ಮುಂಬರುವ ತರಗತಿಗಳು",
  "Draft": "ಕರಡು",
  "What_to_expect": "ಏನನ್ನು ನಿರೀಕ್ಷಿಸಬಹುದು",
  "Start_date": "ಪ್ರಾರಂಭದ ದಿನಾಂಕ",
  "End_date": "ಅಂತಿಮ ದಿನಾಂಕ",
  "Modules_included": "ಸೇರಿಸಲಾದ ಮಾಡ್ಯೂಲ್‌ಗಳು",
  "List_of_modules": "ಮಾಡ್ಯೂಲ್‌ಗಳ ಪಟ್ಟಿ",
  "Content": "ವಿಷಯ",
  "Scorm": "Scorm",
  "Live_sessions": "ಲೈವ್ ತರಗತಿಗಳು",
  "Videos": "ವೀಡಿಯೊಗಳು",
  "Notes": "ಟಿಪ್ಪಣಿಗಳು",
  "Assignment": "ನಿಯೋಜನೆ",
  "Define_your_self":
      "ನಿಮ್ಮ ಸ್ವ-ಗುರಿಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ ಮತ್ತು ಮತ್ತು ನಿಮ್ಮ ಸುಧಾರಣೆಯನ್ನು ಹೆಚ್ಚಿಸಿ",
  "Certification": "ಪ್ರಮಾಣೀಕರಣ",
  "My_Analytics": "ನನ್ನ ಅನಾಲಿಟಿಕ್",
  "Team_Analytics": "ತಂಡದ ಅನಾಲಿಟಿಕ್ಸ್",
  "KPI_Analytics": "ಕೆಪಿಐ ಅನಾಲಿಟಿಕ್ಸ್",
  "Course_level_Analysis": "ಕೋರ್ಸ್ ಮಟ್ಟದ ವಿಶ್ಲೇಷಣೆ",
  "Module_level_Analysis": "ಮಾಡ್ಯೂಲ್ ಮಟ್ಟದ ವಿಶ್ಲೇಷಣೆ",
  "Leaderboard": "ಲೀಡರ್‌ಬೋರ್ಡ್",
  "Switch_to_modules": "ಮಾಡ್ಯೂಲ್‌ಗಳಿಗೆ ಬದಲಿಸಿ",
  "Switch_to_leaderboard": "ಲೀಡರ್‌ಬೋರ್ಡ್‌ಗೆ ಬದಲಿಸಿ",
  "Completed": "ಪೂರ್ಣಗೊಂಡಿದೆ",
  "Score": "ಅಂಕಗಳು",
  "Course_name": "ಕೋರ್ಸ್ ಹೆಸರು",
  "KPIs_assigned": "ಕೆಪಿಐಗಳನ್ನು ನಿಯೋಜಿಸಲಾಗಿದೆ",
  "Monthly_performance": "ತಿಂಗಳ ಕಾರ್ಯ ಕ್ಷಮತೆ",
  "My_certificates": "ನನ್ನ ಪ್ರಮಾಣಪತ್ರಗಳು",
  "Your_medals": "ನಿಮ್ಮ ಪದಕಗಳು",
  "Certificates": "ಪ್ರಮಾಣಪತ್ರಗಳು",
  "Set_your_goals":
      "ಕೆಳಗಿನ  ಕ್ಯಾಲ್ಕುಲೇಟರ್‌ನಲ್ಲಿ (ಗಣಕ) ನಿಮ್ಮ ಗುರಿಗಳನ್ನು ತುಂಬಿಸ ಮತ್ತು ಗುರಿಯನ್ನು ತಲುಪಲು ಅಗತ್ಯವಾದ ದರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "Select_your_goal": "ನಿಮ್ಮ ಗುರಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "Calculate_now": "ಈಗ ಲೆಕ್ಕ ಹಾಕಿ",
  "Billed_outlets": "ಬಿಲ್ಡ್ ಮಳಿಗೆಗಳು",
  "Targeted_outlets": "ಉದ್ದೇಶಿತ ಮಳಿಗೆಗಳು",
  "Target": "ಗುರಿ",
  "Currently_achieved": "ಪ್ರಸ್ತುತ ಸಾಧಿಸಿದ್ದು",
  "Total_MSS_Points": "ಒಟ್ಟು ಎಂಎಸ್ಎಸ್ ಅಂಕಗಳು",
  "Calculated_asking-rate": "ನಿಗದಿಪಡಿಸಿದ ಆಸ್ಕಿಂಗ್ ರೇಟ್",
  "Manage_your_everyday": "ಮುಂದಿನದಕ್ಕೆ",
  "Days": "ದಿನಗಳು",
  "Details": "ವಿವರಗಳು",
  'time': "ಸಮಯ",
  'duration': "ಅವಧಿ",
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/Create account to continue',
  'phone_number': 'Phone number',
  'continue': 'continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and Conditions & Privacy Policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'verification_title': "Enter OTP that sent to",
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  "resend": "Re-send",
  "code_in": "Resend OTP",
  'tell_us_about_yourself': "Tell us about yourself",
};

const MR_TEXT = {
  "alert": "चेतावणी",
  "login": "लॉगिन",
  "logout": "लॉग आऊट",
  "edit_portfolio": "Edit Portfolio",
  "no": "नाही",
  "yes": "होय",
  "profile_title": "प्रोफाइल",
  "cancel": "रद्द करा",
  "take_a_picture": "एक चित्र घ्या",
  "pick_from_gallery": "गॅलरीमधून निवडा",
  "ok": "ठीक आहे",
  "loading": "लोड करीत आहे...",
  "submit": "प्रस्तुत करणे",
  "announcements": "घोषणा",
  "training": "प्रशिक्षण",
  "mandatory_courses": "अनिवार्य अभ्यासक्रम",
  "library": "लाईब्ररी",
  "attachFile": "Attach file",
  "analytics": "विश्लेषणे",
  "my_certificates": "माझी प्रमाणपत्रे",
  "asking_rate_calculator": "आस्किंग रेट कॅल्क्युलेटर",
  "create_a_session": "एक सत्र तयार करा",
  "scheduled_sessions": "नियोजित सत्रे",
  "feedback": "फ़ीडबैक",
  "survey": "सर्वेक्षण",
  "language": "भाषा",
  "account_settings": "खाते सेटिंग्ज",
  "FAQs": "सामान्य प्रश्न",
  "contact_us": "आमच्याशी संपर्क साधा",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "सर्व पहा",
  "start_survey": "सर्वेक्षण सुरू करा",
  "announcement_filters": "घोषणा फिल्टर",
  "write_feedback": "एक फ़ीडबैक लिहा",
  "write_an_idea": "कल्पना लिहा",
  "library_filters": "लायब्ररी फिल्टर",
  "notifications": "अधिसूचना",
  "profile": "प्रोफाइल",
  "address": "पत्ता",
  "landmark": "खूण",
  "post_office": "पोस्ट ऑफिस",
  "city": "शहर",
  "state": "राज्य",
  "save_changes": "बदल सेव्ह करा",
  "save": "सेव्ह",
  "app_language": "अनुप्रयोग भाषा",
  "content_language": "माहिती भाषा",
  "choose_app_language": "अ‍ॅप भाषा निवडा",
  "choose_content_language": "माहिती भाषा निवडा",
  "first_name": "पहिले नाव",
  "last_name": "आडनाव",
  "date_of_birth": "जन्म तारीख",
  "mobile_number": "मोबाइल नंबर",
  "email_address": "ईमेल पत्ता",
  "title": "शीर्षक",
  "topic": "विषय",
  "description": "वर्णन",
  "select_app_language": "अ‍ॅप भाषा निवडा",
  "language_option": "आपण नंतर भाषा पर्यायातून ते बदलू शकता",
  "select_content_language": "माहिती भाषा निवडा",
  "update_version_title": "अपडेट उपलब्ध",
  "update_version_text1": "एक नवीन आवृत्ती उपलब्ध आहे. आपण अ‍ॅप अपडेट कराल?",
  "update_version_text2": "एक नवीन आवृत्ती उपलब्ध आहे. कृपया अ‍ॅप अपडेट करा.",
  "forgot_pass": "संकेतशब्द (पासवर्ड) विसरलो",
  "photo_alert": "फोटो सेट करा",
  "take_a_video": "व्हिडिओ घ्या",
  "pick_a_video": "एक व्हिडिओ निवडा",
  "pick_a_file": "एक फाइल निवडा",
  "verification": "सत्यापन",
  "you_can_change_langauge": "आपण नंतर भाषा पर्यायातून ते बदलू शकता",
  "submitted": "सबमिट",
  "choose_language": "भाषा निवडा",
  "update_profile": "Update My Space",
  "gender": "लिंग",
  "male": "नर",
  "female": "मादी",
  "faqTitle1": "मी अध्याय / मॉड्यूलमध्ये प्रवेश करण्यास सक्षम नाही.",
  "faqTitle2": "मी लाइव्ह वर्गात प्रवेश करण्यास सक्षम नाही.",
  "faqTitle3": "अ‍ॅपमध्ये लॉग इन केल्यानंतर मी विषयाची भाषा बदलू शकतो का?",
  "faqTitle4":
      "एकदा मी कोणतीही भाषा निवडल्यानंतर, प्रत्येक वेळी मी अ‍ॅप उघडताना मला ती निवडण्याची आवश्यकता आहे काय?",
  "faqTitle5": "मागील अ‍ॅपमध्ये आधीच पूर्ण झालेल्या प्रशिक्षणांचे काय होईल?",
  "faqTitle6": "आम्ही अॅपवरून विषय डाउनलोड करू शकतो का?",
  "faqTitle7":
      "आस्किंग रेट कॅल्क्युलेटर मध्ये, काही वापरकर्त्यांकडे सोमवार / मंगळवार इत्यादी साप्ताहिक सुट्टी असते. आम्ही त्याचा ट्रैक कसा करू शकतो?",
  "faq2": "A. प्रशिक्षणातील लाइव्ह वर्ग -\nजर विशिष्ट प्रशिक्षणातील लाइव्ह प्रक्षेपणातील सर्व वर्ग पाहण्याची तुमची इच्छा असल्यास, ट्रैनिंग मधील दुव्याचे अनुसरण करुन, फक्त लाइव्ह वर्ग टॅबवर क्लिक करुन आपण उपलब्ध लाइव्ह वर्गांमध्ये सामील होऊ शकता.\n\n"
      "B. मॉड्यूल मधील लाइव्ह वर्ग -\nजर तुम्हाला मॉड्यूलशी संबंधित लाइव्ह वर्ग पहायचे असतील तर फक्त प्रशिक्षणावर क्लिक करा. यामुळे सर्व मॉड्यूलची यादी आपल्या समोर येईल. मॉड्यूलमधून नॅव्हिगेट केल्यानंतर आपल्याला सर्व प्रशिक्षणांची यादी दिसेल. त्यानंतर आपण उपलब्ध लाइव्ह वर्गत सामील होऊ शकता.\n\n"
      "C. घोषणांमधील लाइव्ह वर्ग -\nजर आपणांस हायलाइट्स (ठळक गोष्टी) मधील लाइव्ह वर्ग पहायचे असल्यास, केवळ हायलाइट्सवर क्लिक करा. सूचीबद्ध क्रियाकलापांमधून नेव्हिगेट करा. त्यानंतर आपण उपलब्ध लाइव्ह वर्गमध्ये सामील होऊ शकता.\n\n"
      "D. लाइव्ह सत्र पाहण्यास सक्षम नाही. –\nआपण लाइव्ह सत्र पाहण्यास सक्षम नसल्यास, वरच्या उजव्या ब्राउझर विंडोमधील ब्लॉक तपासा. ब्लॉक वर क्लिक करा आणि परवानगी तपासा. https://swayam.pvmi.in/img/step.jpg",
  "faq1":
      "रैनिंग मधील दुव्याचे अनुसरण करा, तुम्हाला सर्व प्रशिक्षणांची यादी मिळेल. त्यातील निर्दिष्ट प्रशिक्षणावर क्लिक केल्यानंतर आपण सर्व मॉड्यूल्समध्ये नेव्हिगेट करू शकता.",
  "faq3":
      "हो, मेनूमधील भाषा पर्यायावर जा आणि तेथे आपण अ‍ॅपसाठी तसेच विषयासाठी भाषा निवडू शकतो।",
  "faq4":
      "नाही, एकदाच वापरकर्त्याला भाषा निवडावी लागेल. हे अ‍ॅपमध्ये सेव्ह होईल. परंतु वापरकर्ता भाषा बदलणे निवडू शकतो.",
  "faq5":
      "रिपोर्टमध्ये ते पूर्ण होईल अस दिसेल परंतु अ‍ॅपवर दर्शविण्यासाठी, बॅकएंडमधून पूर्ण होण्यास थोडा वेळ लागेल.",
  "faq6": "नाही, विषय डाउनलोड पर्याय अॅपमध्ये उपलब्ध नाही.",
  "faq7":
      "सामान्य प्रमाण म्हणून आम्ही रविवारी साप्ताहिक सुट्टी मानली आहे आणि मनुष्य-दिवस गणनासाठी आठवड्यातून 6 दिवस ठेवतो. तसेच जवळजवळ उपलब्ध मनुष्य-दिवस उल्लेख केला आहे",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "आयडिया फॅक्टरी",
  "Create_Live_Class": "लाइव्ह क्लास तयार करा",
  "Schedule_Now": "नियोजन करा",
  "Create_a_Session": "एक सत्र तयार करा",
  "Select_Title": "शीर्षक निवडा",
  "Select_Date": "तारीख निवडा",
  "Invite_learners": "विद्यार्थ्यांना आमंत्रित करा",
  "Members_added": "सदस्य जोडले",
  "Publish_Now": "आता प्रकाशित करा",
  "Save_as_draft": "ड्राफ़्ट म्हणून सेव करा",
  "Schedules_Sessions": "नियोजित सत्रे",
  "Upcoming_Sessions": "आगामी सत्रे",
  "Draft": "ड्राफ़्ट",
  "What_to_expect": "काय अपेक्षा करावी",
  "Start_date": "प्रारंभ तारीख",
  "End_date": "शेवटची तारीख",
  "Modules_included": "समाविष्ट मॉड्यूल",
  "List_of_modules": "मॉड्यूल यादी",
  "Content": "विषय",
  "Scorm": "Scorm",
  "Live_sessions": "लाइव सत्रे",
  "Videos": "व्हिडिओ",
  "Notes": "नोट्स",
  "Assignment": "असाइनमेंट",
  "Define_your_self":
      "आपली स्व-लक्ष्ये परिभाषित करा आणि आपल्या सुधारणाला चालना द्या",
  "Certification": "प्रमाणन",
  "My_Analytics": "माझे विश्लेषणे",
  "Team_Analytics": "टीम विश्लेषणे",
  "KPI_Analytics": "केपीआय विश्लेषणे",
  "Course_level_Analysis": "कोर्स स्तराचे विश्लेषण",
  "Module_level_Analysis": "मॉड्यूल स्तराचे विश्लेषण",
  "Leaderboard": "लीडरबोर्ड",
  "Switch_to_modules": "मॉड्यूलवर स्विच करा",
  "Switch_to_leaderboard": "लीडरबोर्डवर स्विच करा",
  "Completed": "पूर्ण",
  "Score": "अंक",
  "myclasses": "मेरी कक्षा",
  "Course_name": "कोर्सचे नाव",
  "KPIs_assigned": "केपीआय नियुक्त केले आहेत",
  "Monthly_performance": "मासिक कामगिरी",
  "My_certificates": "माझी प्रमाणपत्रे",
  "Your_medals": "आपली पदके",
  "Certificates": "प्रमाणपत्रे",
  "Set_your_goals":
      "कॅल्क्युलेटरमध्ये आपले लक्ष्य सेट करा आणि ध्येय पूर्ण करण्यासाठी आवश्यक दराचा मागोवा घ्या",
  "Select_your_goal": "आपले ध्येय निवडा",
  "Calculate_now": "आता गणना करा",
  "Billed_outlets": "बिल्ड आउटलेट्स",
  "Targeted_outlets": "लक्ष्यित आउटलेट्स",
  "Target": "लक्ष्य",
  "Currently_achieved": "सध्या साध्य",
  "Total_MSS_Points": "एकूण एमएसएस पॉइंट्स",
  "Calculated_asking_rate": "गणना केलेल्या आस्किंग रेट",
  "Manage_your_everyday":
      "मोठे परिणाम साध्य करण्यासाठी आपला दररोज व्यवस्थापित करा",
  "For_next": "पुढील साठी",
  "Days": "दिवस",
  "Details": "तपशील",
  'time': "वेळ",
  'duration': "कालावधी",
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/Create account to continue',
  'phone_number': 'Phone number',
  'continue': 'continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and Conditions & Privacy Policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'verification_title': "Enter OTP that sent to",
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  "resend": "Re-send",
  "code_in": "Resend OTP",
  'tell_us_about_yourself': "Tell us about yourself",
};

const ML_TEXT = {
  "alert": "അലേർട്ട്",
  "login": "ലോഗിൻ",
  "logout": "ലോഗൗട്ട്",
  "edit_portfolio": "Edit Portfolio",
  "no": "ഇല്ല",
  "yes": "അതെ",
  "profile_title": "പ്രൊഫൈൽ",
  "cancel": "ക്യാൻസൽ",
  "take_a_picture": "ഫോട്ടോ പകർത്തുക",
  "pick_from_gallery": "ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക",
  "ok": "ശരി",
  "loading": "ലോഡിംഗ്...",
  "submit": "സമർപ്പിക്കുക",
  "announcements": "അറിയിപ്പുകൾ",
  "training": "പരിശീലനങ്ങൾ",
  "mandatory_courses": "നിർബന്ധിത കോഴ്‌സുകൾ",
  "library": "ലൈബ്രറി",
  "analytics": "വിശകലന വിവരങ്ങൾ",
  "my_certificates": "എന്റെ സർട്ടിഫിക്കറ്റുകൾ",
  "asking_rate_calculator": "നിരക്ക് കണക്കാക്കാൻ ആവശ്യപ്പെടുക",
  "create_a_session": "ഒരു സെഷൻ സൃഷ്ടിക്കുക",
  "scheduled_sessions": "ഷെഡ്യൂൾ ചെയ്യപ്പെട്ട സെഷനുകൾ",
  "feedback": "പ്രതികരണം",
  "survey": "അഭിപ്രായ ശേഖരണം",
  "language": "ഭാഷ",
  "account_settings": "അക്കൗണ്ട് സെറ്റിങ്ങ്സ്",
  "FAQs": "ചോദ്യോത്തരങ്ങൾ",
  "attachFile": "Attach file",
  "contact_us": "ഞങ്ങളെ ബന്ധപെടുക",
  "about_perfetti_Joy": "About Perfetti Swayam",
  "view_all": "എല്ലാം കാണുക",
  "start_survey": "സർവേ ആരംഭിക്കുക",
  "announcement_filters": "പ്രഖ്യാപന ഫിൽട്ടറുകൾ",
  "write_feedback": "പ്രതികരണം രേഖപ്പെടുത്തുക",
  "write_an_idea": "ഒരു ആശയം എഴുതുക",
  "library_filters": "ലൈബ്രറി ഫിൽട്ടറുകൾ",
  "notifications": "അറിയിപ്പുകൾ",
  "profile": "പ്രൊഫൈൽ",
  "address": "മേൽവിലാസം",
  "landmark": "ലാൻഡ്മാർക്ക്",
  "post_office": "പോസ്റ്റ് ഓഫീസ്",
  "city": "നഗരം",
  "state": "സംസ്ഥാനം",
  "save_changes": "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
  "save": "സേവ്",
  "app_language": "അപ്ലിക്കേഷൻ ഭാഷ",
  "content_language": "ഉള്ളടക്ക ഭാഷ",
  "choose_app_language": "അപ്ലിക്കേഷൻ ഭാഷ തിരഞ്ഞെടുക്കുക",
  "choose_content_language": "ഉള്ളടക്ക ഭാഷ തിരഞ്ഞെടുക്കുക",
  "first_name": "പേരിന്റെ ആദ്യഭാഗം",
  "last_name": "പേരിന്റെ അവസാന ഭാഗം",
  "date_of_birth": "ജനനത്തീയതി",
  "mobile_number": "മൊബൈൽ നമ്പർ",
  "email_address": "ഈ - മെയില് അഡ്രസ്",
  "title": "ടൈറ്റിൽ",
  "topic": "വിഷയം",
  "description": "വിവരണം",
  "select_app_language": "അപ്ലിക്കേഷൻ ഭാഷ തിരഞ്ഞെടുക്കുക",
  "language_option":
      "നിങ്ങൾക്ക് ഇത് \"ഭാഷാ\" ഓപ്ഷനിൽ നിന്ന് പിന്നീട് തിരുത്താൻ സാധിക്കും",
  "select_content_language": "ഉള്ളടക്ക ഭാഷ തിരഞ്ഞെടുക്കുക",
  "update_version_title": "Update available",
  "update_version_text1":
      "A new version is available. Would you like to update the app?",
  "update_version_text2": "A new version is available. Please update the app.",
  "forgot_pass": "Forgot password",
  "photo_alert": "Set a photo",
  "take_a_video": "Take a Video",
  "pick_a_video": "Pick a Video",
  "pick_a_file": "Pick a File",
  "verification": "Verification",
  "you_can_change_langauge":
      "നിങ്ങൾക്ക് ഇത് \"ഭാഷാ\" ഓപ്ഷനിൽ നിന്ന് പിന്നീട് തിരുത്താൻ സാധിക്കും",
  "submitted": "സമർപ്പിച്ചു",
  "choose_language": "ഭാഷ തിരഞ്ഞെടുക്കുക",
  "update_profile": "Update My Space",
  "gender": "ലിംഗഭേദം",
  "male": "ആൺ",
  "female": "പെൺ",
  "faqTitle1":
      "എനിക്ക് അധ്യായങ്ങൾ / മൊഡ്യൂളുകളിലേക്കു  പ്രവേശിക്കാൻ സാധിക്കുന്നില്ല.",
  "faqTitle2": "എനിക്ക് തത്സമയ ക്ലാസ്സിലേക്ക് പ്രവേശിക്കുവാൻ സാധിക്കുന്നില്ല.",
  "faqTitle3":
      "ചോദ്യം : ആപ്പിൽ ലോഗ് ഇൻ ചെയ്തതിന് ശേഷം ഇടയ്ക്ക് വെച്ച് എനിക്ക് ഭാഷ മാറ്റുവാൻ സാധിക്കുമോ? ",
  "faqTitle4":
      "ചോദ്യം :ഭാഷ ഒരിക്കൽ തിരഞ്ഞെടുത്ത ശേഷം, ഓരോ തവണ ആപ്പിൽ ലോഗ് ഇൻ ചെയ്യുമ്പോഴും ഭാഷ തിരഞ്ഞെടുക്കേണ്ടതുണ്ടോ? ",
  "faqTitle5":
      "ചോദ്യം :മുൻപത്തെ ആപ്പിൽ പൂർത്തീകരിച്ച ട്രെയിനിങ്ങുകൾക്ക് എന്ത് സംഭവിക്കും? ",
  "faqTitle6": "ചോദ്യം :ആപ്പിൽ നിന്ന് ഉള്ളടക്കം ഡൗൺലോഡ് ചെയ്യാൻ ആകുമോ?",
  "faqTitle7":
      "ചോദ്യം : ചോദ്യനിരക്ക് കാൽക്കുലേറ്ററിൽ , ചില ഉപയോക്താക്കളുടെ പ്രതിവാരഅവധി  തിങ്കൾ / ചൊവ്വാഴ്ചകളിൽ ആകാം. ഞങ്ങൾ അത് എങ്ങനെ ട്രാക്കുചെയ്യും?",
  "faq2": "A. ഒരു പരിശീലനത്തിലെ  തത്സമയ ക്ലാസ് -\nനിർദ്ദിഷ്ട പരിശീലനത്തിൽ എല്ലാ തത്സമയ ക്ലാസുകളും കാണണമെങ്കിൽ, പരിശീലനത്തിൽ നിന്നുള്ള ലിങ്ക് പിന്തുടരുക, തത്സമയ ക്ലാസ് ടാബിൽ ക്ലിക്കുചെയ്യുക, നിങ്ങൾക്ക് ലഭ്യമായ തത്സമയ ക്ലാസുകളിൽ പ്രവേശിക്കാം.\n\n"
      "B. ഒരു മൊഡ്യൂളിലെ തത്സമയ ക്ലാസ് -\nമൊഡ്യൂളിന് മാത്രമായുള്ള തത്സമയ ക്ലാസുകൾ കാണാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുവെങ്കിൽ, പരിശീലനത്തിൽ ക്ലിക്കുചെയ്യുക, നിങ്ങൾക്ക് എല്ലാ മൊഡ്യൂളുകളുടെയും പട്ടിക ലഭിക്കും. മൊഡ്യൂളിലൂടെ നാവിഗേറ്റുചെയ്യുക, നിങ്ങൾക്ക് എല്ലാ പരിശീലനങ്ങളുടെയും പട്ടിക കാണാനാകും. തുടർന്ന് നിങ്ങൾക്ക് ലഭ്യമായ തത്സമയ ക്ലാസിൽ പ്രവേശിക്കാം.\n\n"
      "C. ഒരു പ്രഖ്യാപനത്തിലെ തത്സമയ ക്ലാസ് -\nഹൈലൈറ്റുകൾക്ക് മാത്രമായുള്ള തത്സമയ ക്ലാസുകൾ കാണാൻ നിങ്ങൾ ആഗ്രഹിക്കുന്നുവെങ്കിൽ, ഹൈലൈറ്റുകളിൽ ക്ലിക്കുചെയ്യുക. ലിസ്റ്റുചെയ്‌ത പ്രവർത്തനങ്ങളിലൂടെ നാവിഗേറ്റുചെയ്യുക. തുടർന്ന് നിങ്ങൾക്ക് ലഭ്യമായ തത്സമയ ക്ലാസുകളിൽ പ്രവേശിക്കാം.\n\n"
      "D. തത്സമയ സെഷൻ കാണാൻ സാധിക്കുന്നില്ല –\nനിങ്ങൾക്ക് തത്സമയ സെഷൻ കാണാൻ കഴിയുന്നില്ലെങ്കിൽ,  browser വിൻഡോയിലെ മുകളിൽ വലത്തേ അറ്റത്തുള്ള ബ്ലോക്ക് പരിശോധിക്കുക. ബ്ലോക്കിൽ ക്ലിക്കുചെയ്ത് \"അനുവദിക്കുക\" എന്ന് അമർത്തുക . തുടർന്ന് ചിത്രം: https://swayam.pvmi.in/img/step.jpg",
  "faq1":
      "പരിശീലനത്തിൽ നിന്നുള്ള ലിങ്ക് പിന്തുടരുക, എല്ലാ പരിശീലനങ്ങളുടെയും പട്ടിക നിങ്ങൾക്കു കണ്ടെത്താനാകും. നിർദ്ദിഷ്ട പരിശീലനത്തിൽ ക്ലിക്കുചെയ്യുക, നിങ്ങൾക്ക് എല്ലാ മൊഡ്യൂളുകളിലൂടെയും നാവിഗേറ്റ് ചെയ്യാൻ സാധിക്കും.",
  "faq3":
      "ഉത്തരം : സാധിക്കും, മെനുവിലെ ഭാഷ എന്ന ഓപ്ഷനിൽ പോകുക.  അവിടെ നിങ്ങൾക്ക് ആപ്പിനും ഉള്ളടക്കത്തിനും ഉള്ള ഭാഷകൾ തിരഞ്ഞെടുക്കാവുന്നതാണ്. ",
  "faq4":
      "ഉത്തരം :ഇല്ല, ഭാഷ ഒരിക്കൽ മാത്രം തിരഞ്ഞെടുത്താൽ മതി. അത് ആപ്പിൽ സേവ് ചെയ്യപ്പെടും. എന്നാൽ, ഉപയോക്താവിന് എപ്പോൾ വേണമെങ്കിലും ഭാഷ മാറ്റാവുന്നതാണ്. ",
  "faq5":
      "ഉത്തരം :മുൻപ് പൂർത്തീകരിച്ച ട്രെയിനിങ്ങുകൾ റിപ്പോർട്ടുകളിൽ പൂർത്തീകരിച്ചതായി കാണിക്കും. എന്നാൽ ആപ്പിൽ പൂർത്തീകരിച്ചു എന്ന് കാണിക്കുവാൻ അല്പം സമയം എടുക്കും. ",
  "faq6": "ഉത്തരം :ഇല്ല, ആപ്പിൽ ഡൗൺലോഡ് ഓപ്ഷൻ ലഭിക്കുകയില്ല. ",
  "faq7":
      "ഉത്തരം : ഒരു സാധാരണ മാനദണ്ഡമെന്ന നിലയിൽ പ്രതിവാരഅവധി ഞായറാഴ്ച ആയി നിഗമിക്കുന്നു.   മനുഷ്യദിന  കണക്കുകൂട്ടലിനായി ആഴ്ചയിൽ 6  ദിവസം  ഞങ്ങൾ പരിഗണിക്കുന്നു. ഏകദേശം ലഭ്യമാകുന്ന മനുഷ്യദിനങ്ങൾ  ആണ്  സൂചിപ്പിച്ചിരിക്കുന്നത്.",
  "faq8":
      "For detailed information and T&Cs, please click on the Terms and Conditions section on Menu bar.",
  "faq9":
      "No, Perfetti Swayam has exclusively been designed to engage with PVMI distributors through especially designed relationship initiates and which is not determined by their business value with PVMI.",
  "faq10":
      "You will be informed well in advance about any campaign / activity which will be launched under the program through SMS on your registered mobile number, Perfetii Swayam Mobile App and Program Helpdesk",
  "faq11":
      "Every activity or campaign rolled out would be different from the other. The rewards/ benefits earned under such activities would be sent to you through PVMI representative. However, the program team will keep you posted for any such reward/ benefits deliveries.",
  "Idea_Factory": "ഐഡിയ ഫാക്ടറി",
  "Create_Live_Class": "തത്സമയ ക്ലാസ് സൃഷ്‌ടിക്കുക",
  "Schedule_Now": "ഇപ്പോൾ ഷെഡ്യൂൾ ചെയ്യുക",
  "Create_a_Session": "ഒരു സെഷൻ സൃഷ്ടിക്കുക",
  "Select_Title": "ശീർഷകം തിരഞ്ഞെടുക്കുക",
  "Select_Date": "തീയതി തിരഞ്ഞെടുക്കുക",
  "Invite_learners": "പഠിതാക്കളെ ക്ഷണിക്കുക",
  "Members_added": "അംഗങ്ങളെ ചേർത്തു",
  "Publish_Now": "ഇപ്പോൾ പ്രസിദ്ധീകരിക്കുക",
  "Save_as_draft": "ഡ്രാഫ്റ്റ് ആയി സേവ് ചെയ്യുക",
  "Schedules_Sessions": "ഷെഡ്യൂൾ ചെയ്യപ്പെട്ട സെഷനുകൾ",
  "Upcoming_Sessions": "വരാനിരിക്കുന്ന സെഷനുകൾ",
  "Draft": "ഡ്രാഫ്റ്റ്",
  "What_to_expect": "എന്താണ് പ്രതീക്ഷിക്കേണ്ടത്",
  "Start_date": "ആരംഭിക്കുന്ന തീയതി",
  "End_date": "അവസാന ദിവസം",
  "Modules_included": "ഉൾപ്പെടുത്തിയ മോഡ്യൂളുകൾ",
  "List_of_modules": "മൊഡ്യൂളുകളുടെ പട്ടിക",
  "Content": "ഉള്ളടക്കം",
  "Scorm": "Scorm",
  "Live_sessions": "തത്സമയ സെഷനുകൾ",
  "Videos": "വീഡിയോകൾ",
  "Notes": "കുറിപ്പുകൾ",
  "Assignment": "അസൈൻമെന്റ്",
  "Define_your_self":
      "നിങ്ങളുടെ ലക്ഷ്യങ്ങൾ സ്വയം നിർവചിച്ച് നിങ്ങളുടെ  വളർച്ച മെച്ചപ്പെടുത്തുക ",
  "Certification": "സർട്ടിഫിക്കേഷൻ",
  "My_Analytics": "എന്റെ വിശകലന വിവരങ്ങൾ",
  "Team_Analytics": "ടീമിന്റെ വിശകലന വിവരങ്ങൾ",
  "KPI_Analytics": "കെപിഐ വിശകലന വിവരങ്ങൾ",
  "Course_level_Analysis": "കോഴ്‌സ് ലെവൽ വിശകലനം",
  "Module_level_Analysis": "മൊഡ്യൂൾ ലെവൽ വിശകലനം",
  "Leaderboard": "ലീഡർബോർഡ്",
  "Switch_to_modules": "മൊഡ്യൂളുകളിലേക്ക് മാറുക",
  "Switch_to_leaderboard": "ലീഡർബോർഡിലേക്ക് മാറുക",
  "Completed": "പൂർത്തിയായി",
  "Score": "സ്കോർ",
  "Course_name": "കോഴ്സിന്റെ പേര്",
  "KPIs_assigned": "കെപി‌എകളെ ചുമതലപ്പെടുത്തി",
  "Monthly_performance": "പ്രതിമാസ പ്രകടനം",
  "My_certificates": "എന്റെ സർട്ടിഫിക്കറ്റുകൾ",
  "Your_medals": "നിങ്ങളുടെ മെഡലുകൾ",
  "Certificates": "സർട്ടിഫിക്കറ്റുകൾ",
  "Set_your_goals":
      "ചുവടെയുള്ള കാൽക്കുലേറ്ററിൽ നിങ്ങളുടെ ലക്ഷ്യങ്ങൾ സജ്ജമാക്കുക & ലക്ഷ്യം പൂർത്തിയാക്കാൻ വേണ്ട നിരക്ക് കണ്ടെത്തുക",
  "Select_your_goal": "നിങ്ങളുടെ ലക്ഷ്യം തിരഞ്ഞെടുക്കുക",
  "Calculate_now": "ഇപ്പോൾ കണക്കാക്കുക",
  "Billed_outlets": "ബില്ലുചെയ്ത ഔട്‍ലെറ്റുകൾ",
  "Targeted_outlets": "ടാർഗെറ്റുചെയ്ത ഔട്ലെറ്റുകൾ",
  "Target": "ലക്‌ഷ്യം",
  "Currently_achieved": "നിലവിൽ നേടിയവ",
  "Total_MSS_Points": "മൊത്തം എം എം എസ് പോയിൻറുകൾ",
  "Calculated_asking_rate": "കണക്കാക്കിയ ആവശ്യപ്പെടുന്ന നിരക്ക്",
  "Manage_your_everyday":
      "വലിയ ഫലങ്ങൾ നേടുന്നതിനായി നിങ്ങളുടെ ദൈനംദിനം ചിട്ടപ്പെടുത്തുക",
  "For_next": "അടുത്തതിന് വേണ്ടി",
  "Days": "ദിവസങ്ങൾ",
  "Details": "വിശദാംശങ്ങൾ",
  'time': "സമയം",
  'duration': "കാലാവധി",
  'Lets_start_your_journey': 'Lets start your journey',
  'choose_your_app_language': 'Choose your App Language',
  'giving_your_creativity': 'Giving your Creativity a New Path',
  'login_create_account': 'Login/Create account to continue',
  'phone_number': 'Phone number',
  'continue': 'continue',
  'by_clicking_continue': 'By clicking continue, I accept the',
  'by_clicking_continue_underline': ' Terms and condition & privacy policy',
  'having_trouble': 'Having trouble logging in? Contact us +91 7428096480',
  'change_phone_number': 'Change Phone Number',
  'select_categories': 'Select Categories',
  'select_atleast_category': 'Select atleast 1 Category',
  'verification_title': "Enter OTP that sent to",
  'enter_full_name': 'Enter Full Name',
  'choose_image': 'Choose Image',
  'choose_image_description':
      'Choose from gallery or camera to upload your profile picture',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'choose_profile_image': 'Choose Profile Image',
  'change_profile_image': 'Change Profile Image',
  'phone_already_exists': 'Phone number already exists',
  'use_another_phone': 'Use another phone number',
  'choose_your_interests': 'Choose your interests',
  'select_aleast_six_categories': 'Select atleast 1 category',
  "resend": "Re-send",
  "code_in": "Resend OTP",
  'tell_us_about_yourself': "Tell us about yourself",
};
